### ISSUE TITLE
[QUESTION]: will pymilvus support the http restful APIs

### ISSUE THREAD

**Issue by wallies** [milvus-io/pymilvus#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Will pymilvus just be for grpc or will it eventually wrap the http restful api as well?

**Comment by XuanYang-cn** [comment]
@wallies pymilvus 1.x was used for the ci/cd test of Milvus restful server.

But PyMilvus2.x doesn't support restful APIs and won't plan to do so.

**Comment by wallies** [comment]
Thansk @XuanYang-cn. Any plans to write a rest client?

**Comment by XuanYang-cn** [comment]
> Thansk @XuanYang-cn. Any plans to write a rest client?

@wallies No plan for now.
