### ISSUE TITLE
[Bug]: FieldSchema raised with AttributeError: VARCHAR

### ISSUE THREAD

**Issue by wjy3326** [milvus-io/pymilvus#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

fields = [
    FieldSchema(name="news_id", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="news_cateory", dtype=DataType.VARCHAR),    # string: DataType.VARCHAR
    FieldSchema(name="news_pubtime", dtype=DataType.VARCHAR),
    FieldSchema(name="news_heat", dtype=DataType.INT64),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=100)
]
I set the schema above, and the following error occurs:

    FieldSchema(name="news_cateory", dtype=DataType.VARCHAR),    # string: DataType.VARCHAR
  File "/u01/wangjunyan/anaconda3/envs/recommendation/lib/python3.7/enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: VARCHAR 
How does schema create string format？？

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
@wjy3326 what's your pymilvus version?

**Comment by wjy3326** [comment]
pymilvus 2.0.2 milvus cannot support String schema.  I set the schema：
fields = [
    FieldSchema(name="news_id", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="news_cateory", dtype=DataType.String),    # string: DataType.VARCHAR
    FieldSchema(name="news_pubtime", dtype=DataType.String),
    FieldSchema(name="news_heat", dtype=DataType.INT64),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=100)
]
error occurs.

**Comment by XuanYang-cn** [comment]
@wjy3326 pymilvus2.0.2 doesn't support VARCHAR and STRING, VARCHAR will be supported in pymilvus 2.1

**Comment by XuanYang-cn** [comment]
closing it for fixed and idle
