### ISSUE TITLE
[Bug]: Wrong code and messge: Code and message exception returned when connect fails to connect

### ISSUE THREAD

**Issue by elstic** [milvus-io/pymilvus#1056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The uri parameter of the connect interface consists of the protocol, host and port.
When I enter the wrong protocol test, ci _test outputs " <ConnectionConfigException: (code=Illegal uri: [quic,xxx://localhost:19530], should be in form 'http:// example.com' or 'tcp://6.6.6.6:12345', message=)> (api_request.py:36)"

My uri entry: quic,xxx://localhost:19530

### Expected Behavior

When I enter the wrong entry, the log code should return a non-zero number and the message should be "Illegal uri: ....... "

### Environment details

```markdown
- pymilvus version 2.1.0.dev90
```

**Comment by XuanYang-cn** [comment]
/unassign
Fixed @ pymilvus==2.1.0.dev92
/assign @elstic 
Please help verify

**Comment by elstic** [comment]
Verified, results now as expected
- pymilvus==2.1.0.dev92
