### ISSUE TITLE
[Bug]: Milvus documents guide to use 'max_length_per_row' param for VARCHAR type field, but it does not work

### ISSUE THREAD

**Issue by ttti07** [milvus-io/pymilvus#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[The official document](https://milvus.io/docs/v2.1.x/create_collection.md#Prepare-Schema) guides us to use `max_length_per_low` for VARCHAR type fields.
```py
# This code raise an error
book_name = FieldSchema(
  name="book_name", 
  dtype=DataType.VARCHAR, 
  max_length_per_row=200,
)
```

However, with the code above, I got an error like this:
```
MilvusException: (code=1, message=type param(max_length) should be specified for varChar field of collection {collection_name})
```

Currently `FieldSchema` takes param name `max_length`, instead of taking `max_length_per_row`
```py
# Currently (pymilvus v2.1.0) we have to use max_length like this:
book_name = FieldSchema(
  name="book_name", 
  dtype=DataType.VARCHAR, 
  max_length=200,
)
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory): CentOS 7
- Method of installation (Docker, or from source): docker-compose, milvus standalone
- Milvus version (v0.3.1, or v0.4.0): v2.1.0
- Milvus configuration (Settings you made in `server_config.yaml`): default
```

**Comment by XuanYang-cn** [comment]
https://milvus.io/docs/v2.1.x/create_collection.md#Prepare-Schema

@ttti07 It's a bug, and we've updated it to `max_length` now
