### ISSUE TITLE
[FEATURE]: Read Environment Variables for default connection config

### ISSUE THREAD

**Issue by nexttonever** [milvus-io/pymilvus#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

sometimes, to setup config connection may be  inconvenient when there is multiple milvus-related scripts in a project or when scripts should be run in different environment.
so, it may be nessesary for milvus client to support a way to read config from environment, so that scripts will not be changed in different environment.

**Comment by XuanYang-cn** [comment]
pr #1091
