### ISSUE TITLE
[Bug]: MilvusException(Status.UNEXPECTED_ERROR, fail_reason)

### ISSUE THREAD

**Issue by utopictown** [milvus-io/pymilvus#1123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i got

```
File "/usr/local/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 592, in create_index
    raise MilvusException(Status.UNEXPECTED_ERROR, fail_reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=[UnexpectedError] [json.exception.type_error.302] type must be number, but is null)>
```

error when running create_index

this is my index_params = ```{"index_type": "IVF_PQ", "metric_type":"L2", "params": {"nlist": 16384}}```

### Expected Behavior

successfully create index

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
@utopictown "IVF_PQ" index is lack of "m" parameter, ref: https://milvus.io/docs/v2.1.x/index.md#IVF_PQ

The correct index_param would be:
```python
{"index_type": "IVF_PQ", "metric_type":"L2", "params": {"nlist": 16384, "m": 8}}
```
