### ISSUE TITLE
没有删除指定id的索引的功能吗 

### ISSUE THREAD

**Issue by mrright2019** [milvus-io/pymilvus#113]
**What is your question?**
请问支持删除指定id的功能吗？

**Comment by BossZou** [comment]
Hello, that's not supported yet. What's the specific situation that make you need this function?

**Comment by yhmo** [comment]
你好，非常感谢提问。这个问题的意思有点模糊，是否可以理解为’根据名字删除建立好的索引‘？

**Comment by mrright2019** [comment]
> 你好，非常感谢提问。这个问题的意思有点模糊，是否可以理解为’根据名字删除建立好的索引‘？

是否有根据id删除 更新的操作

**Comment by mrright2019** [comment]
> 您好，尚不支持。什么情况使您需要此功能？

我提取了很多视频的特征，但是提取特征的方法是不断变化的，当我使用同一个id分不同的批次插入了多条条记录的时候，发现在milvus内部并不会自动更新，当前是否有根据id更新或者根据id删除的功能。

**Comment by yhmo** [comment]
是这样的，我们insert接口允许用户给每条向量自定义id，但我们不会对自定义id查重，因为对于海量数据来说，id的查重工作会变成系统瓶颈。如果用户给定自定的id，那应该由用户来保证这些id的唯一性。
实际上，如果在插入的时候不自定义id（把那个id array参数传空的数组进去），Milvus内部会根据时间戳给每条向量生成唯一的id（这个唯一是有保证的，就算两条向量在同一微妙内进来，它们的id也会唯一），这些内部产生的唯一id会通过接口参数返还给调用者，这样调用者就不必纠结于怎样保证id的唯一性。
你提到的根据id来删除向量目前我们是没有的，因为零零碎碎地删除向量意味着查询过程要面临频繁地过滤，给算法和数据调度带来巨大压力。
为了让用户能删除部分数据，我们将在0.6.0提供partition的功能，也就是用户可以对表内的向量数据进行分批处理，可以针对表的某一部分查询，也可以将某一部分数据删除而不影响其他部分。

**Comment by mrright2019** [comment]
> 是这样的，我们insert接口允许用户给每条向量自定义id，但我们不会对自定义id查重，因为对于海量数据来说，id的查重工作会变成系统瓶颈。如果用户给定自定的id，那应该由用户来保证这些id的唯一性。
> 实际上，如果在插入的时候不自定义id（把那个id array参数传空的数组进去），Milvus内部会根据时间戳给每条向量生成唯一的id（这个唯一是有保证的，就算两条向量在同一微妙内进来，它们的id也会唯一），这些内部产生的唯一id会通过接口参数返还给调用者，这样调用者就不必纠结于怎样保证id的唯一性。
> 你提到的根据id来删除向量目前我们是没有的，因为零零碎碎地删除向量意味着查询过程要面临频繁地过滤，给算法和数据调度带来巨大压力。
> 为了让用户能删除部分数据，我们将在0.6.0提供partition的功能，也就是用户可以对表内的向量数据进行分批处理，可以针对表的某一部分查询，也可以将某一部分数据删除而不影响其他部分。

在未来会增加对单条数据的操作吗？

**Comment by yhmo** [comment]
我们确实有考虑提供对单条的删除操作，只是因为一些技术上的原因还未能找到合适的方案去实现。这个需求会放在我们的列表里，等找到合理的解决方案我们就会实现它。

**Comment by BossZou** [comment]
Hello @mrright2019 , In latest pymilvus v0.2.8, we have support to delete vectors. try to use `delete_by_id`. You can find more details [here](https://github.com/milvus-io/pymilvus/blob/master/README.md). And note that you need you [milvus v0.7.0](https://github.com/milvus-io/milvus) or pull docker [images](https://hub.docker.com/r/milvusdb/milvus/tags).

**Comment by wanzhixiao** [comment]
删除索引失败，怎么解决？

collection_name = 't_resume_vec'
collection = Collection(collection_name) 
collection.drop_index()

pymilvus.exceptions.AmbiguousIndexName: <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)>
