### ISSUE TITLE
[BUG] Method has_table not return bool type

### ISSUE THREAD

**Issue by fishpenguin** [milvus-io/pymilvus#114]
**Describe the bug**
I invoked method `has_table` and expect a return bool value, but returns a tuple value

**Steps/Code to reproduce behavior**
The code is as follows:
`
assert client.has_table(table_name) == True
`

Exception oucrred:
`
Traceback (most recent call last):
 File "/Git/GitHub/pymilvus/examples/advanced_example.py", line 174, in <module>
   run()
 File "//Git/GitHub/pymilvus/examples/advanced_example.py", line 140, in run
   create_table()
 File "/Git/GitHub/pymilvus/examples/advanced_example.py", line 36, in create_table
   assert milvus.has_table(table_name) == True
AssertionError
`

**Expected behavior**
N/A

**Environment details**

- Hardware/Softward conditions (OS, CPU, GPU, Memory)
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by BossZou** [comment]
Hello, from V0.2.3 the return value of method `has_table` has been changed, new return type is Status and bool, you can find more details in https://github.com/milvus-io/pymilvus/blob/master/milvus/client/grpc_client.py

**Comment by BossZou** [comment]
fix it. close it
