### ISSUE TITLE
[Bug]: AttributeError: 'Collection' object has no attribute 'get_entity_by_id'

### ISSUE THREAD

**Issue by zhenzi0322** [milvus-io/pymilvus#1144]
```
pymilvus: 2.0.2
```

AttributeError: 'Collection' object has no attribute 'get_entity_by_id'

**Comment by XuanYang-cn** [comment]
@zhenzi0322 We don't have `get_entity_by_id` at 2.x, please use `query` to get entity by id

ref https://github.com/milvus-io/pymilvus/blob/22f588951528f0660bc5ae1aca86b3013cfd4021/examples/hello_milvus.py#L157
