### ISSUE TITLE
[QUESTION]: pymilvus support python aio, like wait client.search()

### ISSUE THREAD

**Issue by ZhengJuCn** [milvus-io/pymilvus#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

pymilvus support python aio, like wait client.search()

otherwise if l call client.search() in fastapi, will block event loop?

**Comment by ZhengJuCn** [comment]
@BossZou

**Comment by ZhengJuCn** [comment]
@BossZou could help answer this question, 3q~~

**Comment by XuanYang-cn** [comment]
@ZhengJuCn Currently, you could use "_async" to make a search async

**Comment by ZhengJuCn** [comment]
@XuanYang-cn but even i use "_async" in http api, because i need to call future.result() wait, it will also block async loop

**Comment by ZhengJuCn** [comment]
thanks a lot, this really help! @Andrew-Chen-Wang

**Comment by Andrew-Chen-Wang** [comment]
This is still a problem, but a PR will come soon to hopefully implement this
