### ISSUE TITLE
[Bug]: The default value for index name is not the same as for create_index() and drop_index() when index name is not passed in

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/pymilvus#1211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Can not drop index when index name is not passed into create_index() and drop_index()

the default value for index name is not the same as for create_index() and drop_index()

![f441f29a-22f0-47e8-87a6-3b6ce0409b4d](https://user-images.githubusercontent.com/12268675/198039836-5be29a60-d633-4f4f-875d-e693878a7d73.jpeg)

![d7666c2b-6048-46ec-a35b-70300d91641f](https://user-images.githubusercontent.com/12268675/198039861-6a2c7969-b6df-4745-9c4e-a29301350c23.jpeg)

### Expected Behavior

when the index name is not passed into create_index() and drop_index(), the index is created, it should can be dropped as well.

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
/assign @zhuwenxing 
/unassign
Please try the latest pymilvus

**Comment by zhuwenxing** [comment]
Working on it!
