### ISSUE TITLE
[QUESTION] Do I need to catch the error myself?

### ISSUE THREAD

**Issue by ReigenAraka** [milvus-io/pymilvus#122]
**What is your question?**
When i use the sdk connect milvus server,if port or ip is wrong,i get a crash.
According to the description of the document, I think I will get a `status('message="', code=)`
```
from milvus import Milvus

milvus = Milvus()
status = milvus.connect('127.0.0.1', 19530)
print(status)
```

**Comment by BossZou** [comment]
Hello. You need catch an exception. If the host  or port is illegal, client will raise a Exception named ParamError. If the server is unreachable, client will raise a Exception named NotConnectError. The status will return only connect successfully.

**Comment by BossZou** [comment]
And In the future we plan to remove status in method `connect`

**Comment by ReigenAraka** [comment]
@BossZou  got it;close this pr.
