### ISSUE TITLE
[Bug]: The service was blocked when calling utility.has_collection()

### ISSUE THREAD

**Issue by bachrour** [milvus-io/pymilvus#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have two services, one is responsible for data insertion and the other is responsible for index building. When the data insertion is completed, the index-building service will be called.
1. Data insertion process: 
create_ collection(A1)->create_ index(A1)-> create_ partition->insert->insert-> .... -> insert
create_ collection(A2)->create_ index(A2)->create_ partition->insert->insert-> .... -> insert

3. Index building process: 
has_ collection(A1)->flush(A1)->release(A1)->create_ index(A1)
has_ collection(A2)->flush(A2)->release(A2)->create_ Index (A2) (edited)

The data insertion process uses 4 threads for concurrent insertion.
When building the A1 index, A2 may continue to insert.
The size of the default segment has not been changed. The data amount of my single partition is less than 1024, so I can only call flush+create by force_ Index to trigger actively

```
def get_collection(collection_name):
    if utility.has_collection(collection_name):
        logger.info(f"exist collection: {collection_name}")
        return Collection(collection_name)

    logger.warning(f"can't find collection: {collection_name}")
    return None
```

In the index-building process, when using "utility.has_ collection (collection_name)" judges whether a collection exists, it is often blocked (it often occurs when this function is called after frequent data insertion). However, when the function is accessed again by another thread, the result can be returned quickly. This interface also does not have a timeout function, which causes threads to be there all the time, consuming resources.

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory): client: ubuntu; server: centos
- Method of installation (Docker, or from source): Docker
- Milvus version (v0.3.1, or v0.4.0): V2.2.0
- Milvus configuration (Settings you made in `server_config.yaml`): default
```

**Comment by XuanYang-cn** [comment]
/assign @bachrour 
/unassign

Please try pymilvus==2.2.1
