### ISSUE TITLE
[QUESTION]:pymilvus.exceptions.ParamError: Params must contains key: 'params'

### ISSUE THREAD

**Issue by mk12306** [milvus-io/pymilvus#1254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

i want to know how to set the 'params' for 'FLAT'

error1:
![image](https://user-images.githubusercontent.com/50614823/207035025-5dd1be0f-c582-4799-9df5-652f1ff4e0ed.png)

![image](https://user-images.githubusercontent.com/50614823/207034958-99889e41-c98a-48be-b586-5e78941e45f1.png)

error2:
![image](https://user-images.githubusercontent.com/50614823/207035153-d328a880-ca14-407b-8787-9d7d94de2413.png)

![image](https://user-images.githubusercontent.com/50614823/207035108-2f0709eb-5877-4318-be36-2c81bb15b9e1.png)

### Anything else?

or where can i find the usage of 'FLAT' index from?

**Comment by XuanYang-cn** [comment]
@mk12306  The following works for me in pymilvus>=2.2.0, what's your pymilvus version?
<img width="459" alt="image" src="https://user-images.githubusercontent.com/51370125/207810789-e8d16964-46c4-4e1a-9e9d-51688f8c67ef.png">

**Comment by XuanYang-cn** [comment]
we should allow no `params` for FLAT index
/assign
/kind bug

**Comment by XuanYang-cn** [comment]
dup to #1163
