### ISSUE TITLE
[Bug]: Issues inserting vectors in via pymilvus

### ISSUE THREAD

**Issue by mahajpuneet** [milvus-io/pymilvus#1255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I write the following script, I face data mismatch exceptions, seems like a valid data type:

```
import pymilvus as milvus
import numpy as np
import pandas as pd
from pymilvus import (
    connections,
    utility,
    FieldSchema,
    CollectionSchema,
    DataType,
    Collection
)
status = connections.connect(host='127.0.0.1', port='19530')
# Load the Credit Card Fraud Detection dataset from Kaggle
df = pd.read_csv('creditcard.csv')

# Split the dataset into training and test sets
train_df = df.sample(frac=0.8, random_state=42)
test_df = df.drop(train_df.index)

# Define the fields for the Milvus collection
vdim = len(df.columns) - 2
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=True),
    FieldSchema(name="user_vector", dtype=DataType.FLOAT_VECTOR, dim=vdim)
]
schema = CollectionSchema(
  fields=fields, 
  description="Credit Card Training Data"
)

from pymilvus import utility
utility.drop_collection("creditcard_train")

collection = Collection(
    name="creditcard_train", 
    schema=schema, 
    using='default', 
    shards_num=2
    )

vectors = train_df.drop(['Time', 'Class'], axis=1).values.tolist()
df_vectors = vectors
appended_vectors = [[i for i in range(len(vectors))], 
                    vectors]

collection.insert((vectors))
```

I face the following error:

```
Input In [11], in <cell line: 3>()
      1 # Create a Milvus collection for the training data
      2 # Insert the training data into Milvus
----> 3 collection.insert((vectors))

File /opt/homebrew/lib/python3.9/site-packages/pymilvus/orm/collection.py:421, in Collection.insert(self, data, partition_name, timeout, **kwargs)
    419 if data is None:
    420     return MutationResult(data)
--> 421 check_insert_data_schema(self._schema, data)
    422 entities = Prepare.prepare_insert_data(data, self._schema)
    424 conn = self._get_connection()

File /opt/homebrew/lib/python3.9/site-packages/pymilvus/orm/schema.py:323, in check_insert_data_schema(schema, data)
    321     i_name = [f.name for f in infer_fields]
    322     t_name = [f.name for f in tmp_fields]
--> 323     raise DataNotMatchException(message=f"The fields don't match with schema fields, expected: {t_name}, got {i_name}")
    325 for x, y in zip(infer_fields, tmp_fields):
    326     if x.dtype != y.dtype:

DataNotMatchException: <DataNotMatchException: (code=1, message=The fields don't match with schema fields, expected: ['user_vector'], got ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 
```

### Expected Behavior

Vectors is a list of lists, ideally it should be insertable as is into the db.

len(vectors) gives 227846
len(vectors[0])
Pasting below the first 2 items in the vectors list(this is essentially Kaggle credit card data set):

[[-16.5265065691231,
  8.58497179585822,
  -18.6498531851945,
  9.50559351508723,
  -13.7938185270957,
  -2.83240429939747,
  -16.701694296045,
  7.51734390370987,
  -8.50705863675898,
  -14.1101844415457,
  5.29923634963938,
  -10.8340064814734,
  1.67112025332681,
  -9.37385858364976,
  0.360805641631617,
  -9.89924654080666,
  -19.2362923697613,
  -8.39855199494575,
  3.10173536885404,
  -1.51492343527852,
  1.19073869481428,
  -1.12767000902061,
  -2.3585787697881,
  0.673461328987237,
  -1.4136996745882,
  -0.46276236139933,
  -2.01857524875161,
  -1.04280416970881,
  364.19],
 [0.33981206391426,
  -2.7437452373292,
  -0.134069510964111,
  -1.3857293091396,
  -1.45141332053475,
  1.01588659391832,
  -0.524379056921013,
  0.224060376080597,
  0.899746004868937,
  -0.565011683648515,
  -0.0876702572804589,
  0.979426987868997,
  0.0768828167722893,
  -0.217883812142159,
  -0.136829587651677,
  -2.14289209021685,
  0.12695606466953,
  1.75266150752555,
  0.432546223730087,
  0.506043885230096,
  -0.213435843580959,
  -0.94252502462284,
  -0.526819174549234,
  -1.15699189743217,
  0.311210510185095,
  -0.7466466791293,
  0.0409958026777039,
  0.102037824570113,
  520.12]]

### Steps/Code To Reproduce behavior

```markdown
If we try the above code as given in description, the error should be reproducable
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by yhmo** [comment]
The field "pk" is auto_id=True, no need to provide values for this field:
**FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=True)**

**Comment by mahajpuneet** [comment]
Thanks folks, sorry for the delay in closure
