### ISSUE TITLE
[QUESTION]: How to implement connection pooling?

### ISSUE THREAD

**Issue by doganMemory** [milvus-io/pymilvus#1268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I searched to understand how to implement connection pooling with pyMilvus but I haven't found that is up to date with the current version. Can you please provide an explanation and if it is possible a simple code snippet to accomplish this?

### Anything else?

From FAQ of documentation:

> Python SDKs for Milvus v0.9.0 or higher have a connection pool. The number of connections in a connection pool has no upper limit.

But it is not clear how and there is no example.

Older versions have a `Milvus` class that has a parameter called `pool`. Now the connections are done through the `Connections` class and this class has an exception (`raises ParamError: If pool in connection parameters is not supported.`).

**Comment by XuanYang-cn** [comment]
@doganMemory connection pooling is available on pymilvus 1.x.

Pymilvus 2.x uses a thread local connection, one connection per thread, no need to worry about the pooling.

/assign @doganMemory 
/unassign
