### ISSUE TITLE
[FEATURE]: It makes no sense that max_length property of VARCHARs be inclusive

### ISSUE THREAD

**Issue by albsenstile** [milvus-io/pymilvus#1289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In method entity_helper.check_str_arr the exception is thrown if len(s) >= max_len

### Describe the solution you'd like

Change the greater_equal condition to greater:
        if len(s) > max_len:
            raise ParamError(message=f"invalid input, length of string exceeds max length. length: {len(s)}, max length: {max_len}")

**Comment by XuanYang-cn** [comment]
Sounds great, are you intend to fix the problem?

/assign @albsenstile

**Comment by albsenstile** [comment]
Not sure how to push the code I fixed: what branch, do I have permissions?...etc.

**Comment by XuanYang-cn** [comment]
Should be fixed by #1304
