### ISSUE TITLE
[BUG] The error message 'Vectors should be 2-dim array!' might be confusing

### ISSUE THREAD

**Issue by yamasite** [milvus-io/pymilvus#133]
**Describe the bug**
The error message 'Vectors should be 2-dim array!' might be confusing. This is also covered in our FAQ. Users are confused when the array is a 2-dim array but the error persists.

**Steps/Code to reproduce behavior**
By this function in utils.py:

```python
def is_legal_array(array):
    if not array or \
       not isinstance(array, list) or \
       len(array) <= 0 or \
       not isinstance(array[0], float):
        return False

    return True
```
We can assume that a legal array must not be empty and must contain only float elements. However, the following message in prepare.py might be confusing:

```python
for vector in query_records:
            if is_legal_array(vector):
                search_param.query_record_array.add(vector_data=vector)
            else:
                raise ParamError('Vectors should be 2-dim array!')

        return search_param
```

**Expected behavior**
The error message could be improved as:

```python
for vector in query_records:
            if is_legal_array(vector):
                search_param.query_record_array.add(vector_data=vector)
            else:
                raise ParamError('A vector must be a non-empty, 2-dimensional array and must 
 contain only elements with the float data type.')

        return search_param
```

**Comment by BossZou** [comment]
I see. Thank you for a good suggestion. The error message will be changed in v0.2.6 soon.

**Comment by yamasite** [comment]
Fixed.
