### ISSUE TITLE
[Bug]: Segmentation fault occurred when import pymilvus

### ISSUE THREAD

**Issue by tw15per** [milvus-io/pymilvus#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Segmentation fault occurred when I execute `import pymilvus`.
![微信图片_20230324134054](https://user-images.githubusercontent.com/104301945/227434375-e2003d75-1cb6-452c-b31b-8012b7de08d0.png)
There is my conda environment.
![微信图片_20230324134102](https://user-images.githubusercontent.com/104301945/227434714-739c7779-d22d-48b5-9d71-80ae0e1d54ee.png)

### Expected Behavior

Import pymilvus without any issue.

### Steps/Code To Reproduce behavior

```markdown
1. conda create -n milvus-dev python=3.10
2. conda activate milvus-dev
3. pip install pymilvus
4. python
5. import pymilvus (This is where I encounter this issue)
```

### Environment details

```markdown
- Hardware/Software conditions (OS, CPU, GPU, Memory): Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-1087-kvm x86_64), 16GiB
- Method of installation (Docker, or from source): Anaconda3 2023.03, Python 3.10.10, pip 23.0.1
- Milvus version (v0.3.1, or v0.4.0): v2.2.3
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by yanliang567** [comment]
@tw15per could you please attach the core dump for investigation?

**Comment by tw15per** [comment]
@yanliang567 Where can I find core dump? I think my system disabled core dump by default, but it did show `Segmentation fault (core dumped)` right? It's so weird that now I enabled core dump but `(core dumped)` never show up again, now it only shows `Segmentation fault`

**Comment by yanliang567** [comment]
it seems like a conda env issue.  please try to 
- uninstall all (or start fresh where nothing was installed)
- install the minimum necessary (I prefer miniconda to anaconda for this reason)
- use a conda environment as a regular user– rather than installing things globally or working as root
Referring to https://groups.google.com/g/gensim/c/AjoAwmnnxiM?pli=1

**Comment by tw15per** [comment]
@yanliang567 Unintsall anaconda and install miniconda helps. Thanks

**Comment by yanliang567** [comment]
great to hear that! :)
