### ISSUE TITLE
[FEATURE]: Support another wrapper for easier integration 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/pymilvus#1368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

A lot of community trying to integrate with Milvus, and we want to save developer's effort to make it easier to integrate for both Milvus and Zilliz cloud.

### Describe the solution you'd like

So why not have a wrapper in pymilvus utils, support similar abstract layer in langchain, make users easier to integrate with only a couple of functions

1. Init -> Decide if it's a milvus or zilliz cloud, connect, did create collection,  create index, load entities.
2. add entities
    mapping user's input into Milvus schema. user could directly insert a map or numpy rather than worry about milvus schema. We do conversion automatically to the redefined collections.
3. search
    filter to be supported later, not now let's to pure Ann search.
4. query
    get the data with filters, fetch output fields....
5. close -> either drop the collection/index or just clean up the connection

**Comment by xiaofan-luan** [comment]
@shanghaikid 
I guess js client should have this abstract layer to.

**Comment by filip-halt** [comment]
The key details are :
- Connect either with new connection or reuse
- Parse an existing collection to figure out what fields are used for what
- if no collection exists at init, wait for first insert to decide on schema (fields, dim, datatypes, etc)

**Comment by xiaofan-luan** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Is your feature request related to a problem? Please describe.
> A lot of community trying to integrate with Milvus, and we want to save developer's effort to make it easier to integrate for both Milvus and Zilliz cloud.
> 
> ### Describe the solution you'd like
> So why not have a wrapper in pymilvus utils, support similar abstract layer in langchain, make users easier to integrate with only a couple of functions
> 
> 1. Init -> Decide if it's a milvus or zilliz cloud, connect, did create collection,  create index, load entities.
> 2. add entities
> 3. search
> 4. close -> either drop the collection/index or just clean up the connection
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Anything else?
> _No response_



> The key details are :
> 
> * Connect either with new connection or reuse
> * Parse an existing collection to figure out what fields are used for what
> * if no collection exists at init, wait for first insert to decide on schema (fields, dim, datatypes, etc)

Yeah，once we support json, there could also be some schema mappings.

**Comment by filip-halt** [comment]
https://github.com/hwchase17/langchain/pull/3047

This is an example of the current flow that is happening. Im going to try to move a majority of the logic into a MilvusClient/VectorStore class that can then be binded to in the integrations.

**Comment by fzliu** [comment]
@filip-halt My preference here is a client interface i.e. `MilvusClient`. Doesn't have to be this though - we should avoid `VectorStore` as Milvus does more than that.

**Comment by xiaofan-luan** [comment]
> @filip-halt My preference here is a client interface i.e. `MilvusClient`. Doesn't have to be this though - we should avoid `VectorStore` as Milvus does more than that.

Make sense to me

**Comment by filip-halt** [comment]
When a user gives us an embedidng function. Do we want to enforce an interface like this?
https://github.com/hwchase17/langchain/blob/0b542661b46d42ee501c6681a4519f2c4e76de23/langchain/embeddings/base.py#L10

We need a way of knowing if the embedding function can act on singular vs multiple documents. I feel like having a parameter to signify this might cause code bloat. This could also help in future integrations with different embedding services.

**Comment by fzliu** [comment]
`pymilvus` shouldn't be privy to the user's embedding function. Insert/query functions can be split into single calls and batch calls (nested list/list of `np.ndarray`).

No need to have more functions than that.

**Comment by xiaofan-luan** [comment]
single call and batch call might be a little bit too much for me~
yes I agree, embedding function won't be our concern for now

**Comment by xiaofan-luan** [comment]
> single call and batch call might be a little bit too much for me~ yes I agree, embedding function won't be our concern for now

I would say 1 call for both single and batch, based on if it's a list or a single entity

**Comment by XuanYang-cn** [comment]
MilvusClient done
