### ISSUE TITLE
[FEATURE]: Support JSON field and Array field in Pymilvus

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/pymilvus#1370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Users want to dynamic schemas.
Milvus don't support alter schema for now, but support JSON and Arrays would be the low hanging fruit.

See https://github.com/milvus-io/milvus/issues/23389

**Comment by XuanYang-cn** [comment]
supported now
