### ISSUE TITLE
[FEATURE]: Remove the logic to fill in the default number of shard when create collection

### ISSUE THREAD

**Issue by czs007** [milvus-io/pymilvus#1377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The default shard number will be filled in the server.

**Comment by xiaofan-luan** [comment]
Yep, Let's keep the default to be 1

**Comment by xiaofan-luan** [comment]
please also make sure all the document has the shard number to be 1
