### ISSUE TITLE
[QUESTION] create_partition中partition_name和partition_tag两个参数有什么区别？

### ISSUE THREAD

**Issue by huanghao128** [milvus-io/pymilvus#142]
create_partition中partition_name和partition_tag两个参数有什么区别，drop_partition和search中用的都是partition_tag，partition_name好像没看到哪里有用到。

**Comment by yhmo** [comment]
每个分区在内部都以一张表的形式存在，这个partition_name就是分区的表名，这个表名是全局唯一的。每个分区都有一个母表，partition_tag是一个标签，用来在母表下面找到对应的分区的，这个标签是在母表表内唯一

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："huanghao "<notifications@github.com&gt;;
发送时间：2020年1月19日(星期天) 中午11:11
收件人："milvus-io/pymilvus" <pymilvus@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[milvus-io/pymilvus] [QUESTION] create_partition中partition_name和partition_tag两个参数有什么区别？ (#142)
-----------------------------------

 
create_partition中partition_name和partition_tag两个参数有什么区别，drop_partition和search中用的都是partition_tag，partition_name好像没看到哪里有用到。

**Comment by yamasite** [comment]
Internally, partitions are also tables, so they need names(table names). You are right that we generally use partition tags for Milvus operations. For more information, please refer to [this blog](https://www.milvus.io/cn/blogs/2019-12-16-table-partition.md#%EF%BC%88%E4%B8%80%EF%BC%89%E4%BB%80%E4%B9%88%E6%98%AF%E5%88%86%E5%8C%BA%EF%BC%9F).

**Comment by huanghao128** [comment]
明白了，博客写的很详细，没仔细看
