### ISSUE TITLE
[QUESTION]: Support for rollback and atomic set of ops like 2PC

### ISSUE THREAD

**Issue by SamSamhuns** [milvus-io/pymilvus#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Is there a way to get atomic operations with rollback and commit in milvus similar to what MySQL has?
Support I want to do two operations: 1 and 2. Op 1 inserts data into a milvus collection while Op 2 does something that has a chance of failing such as writing data to another database or a faulty runtime operation i.e. x=1/0.

Is there a way I can rollback the initial milvus insert operation so that both operations 1 and 2 must succeed or both must fail similar to what is achieved in a 2 Phase Commit (2PC) protocols?

Ideally, I would like to do this with proposed operations such as the milvus.commit() and milvus rollback() and not use a delete operation in the exception handling section.

```python
milvus = Milvus(host='localhost', port='19530')
try:
    # operation 1
    # Insert data into Milvus
    milvus.insert(collection_name='mycollection', records=data)

    # operation 2
    # do something else that has a chance of failing
    # i.e. insert metadata into another database or a failing operation
    x = 1/0 # op that will fail

    # Commit the milvus transaction
    milvus.commit()
except Exception as e:
    # Roll back the milvus transactions so that both ops must succeed or fail
    milvus.rollback()
```

**Comment by xiaofan-luan** [comment]
Milvus is not a transaction database, personally I don't like the idea to support transaction.

**Comment by xiaofan-luan** [comment]
> If there are no plans for this, I am closing this. Right now I maintain the atomicity of the overall function by using transactions with the other non-Milvus operation (mysql/mongo db transactions) and running it before the Milvus ops.

Sure. I will think of keeping atomicity so you can retry after insert failure.
Definitely no transaction support
