### ISSUE TITLE
[Bug]: Search doesn't support vector field as output_fields

### ISSUE THREAD

**Issue by AnthonyTsu1984** [milvus-io/pymilvus#1463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running the example in `dynamic_field.py`, a Milvus exception reports that Search doesn't support vector field as `output_field`.

The original code is 

```python

fields = [
    FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
]

...

start_time = time.time()
result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, output_fields=["pk", "embeddings"])
end_time = time.time()
...

result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, output_fields=["pk", "embeddings", "$meta"])
```

The exception reads 

```python
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=search doesn't support vector field as output_fields)>
```

### Expected Behavior

After I removed the vector field from the output fields, everything goes fine.

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
Sounds like a bug of the example.
/assign @czs007

**Comment by XuanYang-cn** [comment]
dynamic_field.py should be able to run in pymilvus 2.2.x and master. I think we should remove the output_field in search in the example. @czs007

**Comment by XuanYang-cn** [comment]
According to @czs007 there's no bug.
dynamic_field.py in branch 2.2 is the correct version for pymilvus 2.2.x https://github.com/milvus-io/pymilvus/blob/2.2/examples/dynamic_field.py

dynamic_field.py in branch master is the correct version for pymilvus 2.3.x;

So please refer to branch 2.2's example please. @AnthonyTsu1984 

/unassign @czs007 
/assign @AnthonyTsu1984

**Comment by XuanYang-cn** [comment]
Close for idle. Feel free to reopen this issue
