### ISSUE TITLE
[QUESTION]: Is it possible to edit a metadata field ?

### ISSUE THREAD

**Issue by AguirreNicolas** [milvus-io/pymilvus#1553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

**Is it possible to edit a metadata field ?** i.e.,

Some of my entities did not have all the metadata fields completed at the time of insertion. However, now I can complete/edit them using a boolean expression. Is this possible?

If not, what would be the viable methodology?

Something like this?
1) Get the IDs of all the entities in the expression, 
2) Modify/edit the copy of them, 
3) re-upload edited entities (with new IDs), 
4) Finally delete the original IDs/entities.

Many thanks for considering my request.

**Comment by xiaocai2333** [comment]
@AguirreNicolas  Weclome to use milvus. And what means metadata? Have you enabled dynamic fields? You can try using `not` 
 and `exists` expression with your dynamic field key to filter out the data you want to delete. Please feel free to provide more details about your data so that we can help you resolve this issue.

**Comment by AguirreNicolas** [comment]
Sorry for the lack of description, let's try again.

By metadata I mean all FieldSchema different to the embbeding or the primary key.

For example:
```similarity_search_fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, description="id",  is_primary=True, auto_id=True), #
    FieldSchema(name="vector", dtype=DataType.FLOAT_VECTOR, description="embedding", dim=768),
    FieldSchema(name="date", dtype=DataType.INT64, description="source date"), # Unix timestamp
    FieldSchema(name="url", dtype=DataType.VARCHAR, description="url, if exist", max_length=256),
    FieldSchema(name="text", dtype=DataType.VARCHAR, description="complet text, not truncated", max_length=2048),
    ]
```    
In this case I would consider fields date, url and text as "metadata".
    
So the question would be:

Once I insert all of my samples using, for example:

```collection.insert(sample, partition_name=mv_partition)```

There is a way to then edit the content entities' fields like "url", or "text" given a list of primary keys ids?

**Comment by xiaocai2333** [comment]
@AguirreNicolas You can delete these datas by expression `pk in [1, 2, 3...]`, then re-insert datas with new  metadata. We do not currently support `upsert/update`, so can not directly edit the content of the inserted data.

**Comment by AguirreNicolas** [comment]
Thanks, good to know that.
