### ISSUE TITLE
[BUG] Suggest removing version_notes.rst

### ISSUE THREAD

**Issue by yamasite** [milvus-io/pymilvus#162]
**Describe the bug**
https://github.com/milvus-io/pymilvus/blob/master/doc/source/version_notes.rst
The information is not up-to-date and may be misleading.

**Expected behavior**
It is difficult to keep a separate release note for pymilvus. We have a general release note for Milvus. So I believe we can remove this file.

**Comment by BossZou** [comment]
Fixed. Close it.
