### ISSUE TITLE
[Bug]: connections.connect retries connection 75 times when milvus says the credentials are invalid

### ISSUE THREAD

**Issue by realech** [milvus-io/pymilvus#1629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an instance of milvus running with authorizationEnabled set to true and I am trying to connect to it using pymilvus.

In my use case, I have to check whether if a set of credentials is valid or not. Milvus throws the following error when that happens, but it gets retried 75 times before I am able to handle the error:

`WARNING:pymilvus.decorators:[__internal_register] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, auth check failure, please check username and password are correct`

Shouldn't the connect method raise an Exception the first try when seeing the auth check failure, and avoid retrying?
Also, I cannot find a way to set the number of max retries to the connect method, is that possible, if so, how?

Thanks in advance!

### Expected Behavior

When I try to connect to a Milvus instance with authorization enabled, it should fail at the first try if the credentials are invalid

### Steps/Code To Reproduce behavior

```markdown
Run an instance of milvus-standalone in docker and mount the following volume:

`./docker.milvus.yaml:/milvus/configs/milvus.yaml`

The docker.milvus.yaml file is this file here: https://raw.githubusercontent.com/milvus-io/milvus/v2.2.12/configs/milvus.yaml but the following setting edited by setting it to true.


common:
  security:
    authorizationEnabled: true
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory): U
- Method of installation (Docker, or from source): Docker
- Milvus version: v2.2.12
- Pymilvus version: v2.2.14
- Milvus configuration (Settings you made in `server_config.yaml`):


common:
  security:
    authorizationEnabled: true
```

### Anything else?

```
WARNING:pymilvus.decorators:[__internal_register] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, auth check failure, please check username and password are correct>
WARNING:pymilvus.decorators:[__internal_register] retry:5, cost: 0.81s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, auth check failure, please check username and password are correct>
WARNING:pymilvus.decorators:[__internal_register] retry:6, cost: 2.43s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, auth check failure, please check username and password are correct>
WARNING:pymilvus.decorators:[__internal_register] retry:7, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, auth check failure, please check username and password are correct>
WARNING:pymilvus.decorators:[__internal_register] retry:8, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, auth check failure, please check username and password are correct>
WARNING:pymilvus.decorators:[__internal_register] retry:9, cost: 3.00s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, auth check failure, please check username and password are correct>
```

**Comment by SimFG** [comment]
@realech In the next version of pymilvus, the retry has been deleted when the credentials are invalid

**Comment by XuanYang-cn** [comment]
Seems fixed, feel free to reopen this issue

**Comment by Kevinello** [comment]
> @realech In the next version of pymilvus, the retry has been deleted when the credentials are invalid



> Seems fixed, feel free to reopen this issue

i can reproduce it in latest(pymilvus 2.3.2, milvus 2.3.2), when i pass a wrong password, the grpc error server returns will be 2(UNKNOWN), and keep retry as usual
<img width="1330" alt="image" src="https://github.com/milvus-io/pymilvus/assets/56342249/2735f7ce-470f-4866-865e-20e3663bfb1f">
<img width="1008" alt="image" src="https://github.com/milvus-io/pymilvus/assets/56342249/3e62cfc6-4be6-4855-b3d9-b2a9d5186a45">

**Comment by SimFG** [comment]
@Kevinello
Due to some code refactoring reasons, this error appeared again. I will fix it in the milvus
