### ISSUE TITLE
[Bug]: `has_collection` depends on the unreasonable error code

### ISSUE THREAD

**Issue by yah01** [milvus-io/pymilvus#1665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/milvus-io/pymilvus/assets/12216890/0672c417-4249-420f-97e9-b1230bebc9ab)
We are refactoring the error handling in Milvus, when we correct the error code of `DescribeCollection` to `CollectionNotFound`, tests failed

### Expected Behavior

Here it should simply return the bool result from the response 

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
see also: #1696

**Comment by XuanYang-cn** [comment]
fixed and closing
