### ISSUE TITLE
[BUG]: milvus.create_index(collection_name, param)

### ISSUE THREAD

**Issue by Jie-Yuan** [milvus-io/pymilvus#167]
index_param = {
            'index_type': IndexType.FLAT, #IndexType.IVFLAT,  # choice ivflat index
            'nlist': 2048
        }
    
    
milvus.create_index(collection_name, param)

---------------------------------------------------------------------------
ParamError                                Traceback (most recent call last)
<ipython-input-100-62716953e0bd> in <module>
      5 
      6 
----> 7 milvus.create_index(collection_name, param)

/usr/local/lib/python3.6/dist-packages/milvus/client/stub.py in wrapper(self, *args, **kwargs)
     16             raise NotConnectError('Please connect to the server first')
     17 
---> 18         return f(self, *args, **kwargs)
     19 
     20     return wrapper

/usr/local/lib/python3.6/dist-packages/milvus/client/stub.py in create_index(self, collection_name, index_type, params, timeout)
    367         """
    368         _index_type = IndexType.FLAT if index_type is None else index_type
--> 369         check_pass_param(collection_name=collection_name, index_type=_index_type)
    370 
    371         params = params or dict()

/usr/local/lib/python3.6/dist-packages/milvus/client/check.py in check_pass_param(*args, **kwargs)
    243         elif key in ("index_type",):
    244             if not is_legal_index_type(value):
--> 245                 _raise_param_error(key)
    246         elif key == "index_file_size":
    247             if not is_legal_index_size(value):

/usr/local/lib/python3.6/dist-packages/milvus/client/check.py in _raise_param_error(param_name)
    227 
    228 def _raise_param_error(param_name):
--> 229     raise ParamError("{} is illegal".format(param_name))
    230 
    231 

ParamError: index_type is illegal

**Comment by BossZou** [comment]
Hello @Jie-Yuan , The latest pymilvus offer elastic api for different index type, so that the method `create_index` has been changed. You can find more details and exmaple for usage [here](https://github.com/milvus-io/docs/blob/master/site/en/guides/milvus_operation.md#createdrop-indexes-in-a-collection)

**Comment by BossZou** [comment]
You may try like this:
```
index_param = {
   'nlist': 2048
}

milvus.create_index(collection_name, IndexType.FLAT, index_param)
```

**Comment by BossZou** [comment]
Fixed. Will close this issue. .......
