### ISSUE TITLE
[QUESTION]: 对array类型的支持预计什么时候上线

### ISSUE THREAD

**Issue by TristeLXH** [milvus-io/pymilvus#1685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

milvus在2.3.x版本中已经支持json和array类型了，milvus-sdk-java也支持了json和array，但是最新版本的pymilvus还不支持array类型，我看到了有这个merge request，所以想问一下这个预计什么时候上线并发布新版本？

### Anything else?

https://github.com/milvus-io/pymilvus/pull/1681

**Comment by xiaocai2333** [comment]
@TristeLXH please use english on issues. Thanks.
duplicated with #26108, track there.
And the array feature is expected to be released in 2.3.2, so stay tuned!

**Comment by xiaocai2333** [comment]
Other SDKs only support this field. In fact, this function is not supported on Milvus.

**Comment by TristeLXH** [comment]
> Other SDKs only support this field. In fact, this function is not supported on Milvus.

got it, thanks
