### ISSUE TITLE
[Bug]: Pass extra params

### ISSUE THREAD

**Issue by smellthemoon** [milvus-io/pymilvus#1714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="954" alt="image" src="https://github.com/milvus-io/pymilvus/assets/64083300/16b85f25-3c04-46c7-b33d-05df328f11c6">

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
fixed and close
