### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'milvus'

### ISSUE THREAD

**Issue by naarkhoo** [milvus-io/pymilvus#1720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when I do "python -c "from milvus import Milvus, DataType"" I get "ModuleNotFoundError: No module named 'milvus'"

I am using 

```
"
[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pandas = "^2.1.1"
sentence-transformers = "^2.2.2"
torch = "^2.0.1"
pymilvus = "^2.3.1"
setuptools = "^68.2.2"
"
```
whith pymilvus version "'2.3.1'" and I can import "from pymilvus import Milvus, DataType" but the "MetricType"; in the documentation [here](https://pymilvus.readthedocs.io/en/latest/tutorial.html)  only "pip install pymilvus" is used but later, "milvus" is used.

### Expected Behavior

just to import successfully according to the documentation !

### Steps/Code To Reproduce behavior

```markdown
NA
```

### Environment details

```markdown
- I am using mac OS Monterey
- I have milvus server running through docker and would like to connect using pymilvus
```

### Anything else?

NA

**Comment by XuanYang-cn** [comment]
@naarkhoo The documentation of PyMilvus has been moved into milvus.io, please check it here: https://milvus.io/api-reference/pymilvus/v2.3.x/About.md

The latest documentation hosted on readthedocs are pymilvus v1.1.2. We have some major changes of API between 1.x to 2.x, `Milvus` class was deprecated already.

**Comment by naarkhoo** [comment]
oh I see so I was looking into a wrong documentation;
perhaps I can help you out on that as i am going through it ! is there any to-do to figure out where and how do you need help :-)

**Comment by naarkhoo** [comment]
oh I see so I was looking into a wrong documentation;
perhaps I can help you out on that as i am going through it ! is there any to-do to figure out where and how do you need help :-)
