### ISSUE TITLE
[Bug]: Documentation error, variable capitalization ("metric_type": "L2")

### ISSUE THREAD

**Issue by dannyOhNo** [milvus-io/pymilvus#1724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the getting started documentation (https://milvus.io/docs/v2.0.x/example_code.md), the index is built with a capital "L2". 

```
index = {
    "index_type": "IVF_FLAT",
    "metric_type": "L2",
    "params": {"nlist": 128},
}
hello_milvus.create_index("embeddings", index)
```

In the very next segment, the variable is referenced as lowercase.

```
hello_milvus.load()
vectors_to_search = entities[-1][-2:]
search_params = {
    "metric_type": "l2",
    "params": {"nprobe": 10},
}
result = hello_milvus.search(vectors_to_search, "embeddings", search_params, limit=3, output_fields=["random"])
```

This results in a general exception:

```
RPC error: [search], <MilvusException: (code=1, message=attempt #0: fail to Search, QueryNode ID=3, reason=collection:444581957070783752, metric type not match: expected=L2, actual=l2:
```

Changing the `l2` to `L2` resolves the issue. 

### Expected Behavior

Documentation should contain code samples that run without modificatoin.

### Steps/Code To Reproduce behavior

```markdown
Run the documentation sample code.
```

### Environment details

```markdown
Windows WSL, Ubuntu, pymilvus 2.2.16
```

**Comment by XuanYang-cn** [comment]
@dannyOhNo Good catch, will be fixed soon

**Comment by XuanYang-cn** [comment]
fixed and closing
