### ISSUE TITLE
How to return multiple pieces of data with the same field in the search()  or query() method?

### ISSUE THREAD

**Issue by zhongJY1998** [milvus-io/pymilvus#1737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Hello, the problem I encountered is this. For example, I inserted 5 pieces of data. Each piece of data has 3 fields embedding, query, and answer. However, the contents of my 5 query fields are the same. I searched through When the limit is set to 5 during method search, only one of the data will be returned. How can I return all the data with the same query in these 5 queries?

**Comment by zhongJY1998** [comment]
Primary key content cannot be repeated

**Comment by XuanYang-cn** [comment]
@zhongJY1998 entities with the same pk are considerred dup entities in Milvus, there's no way to get them all back by search or query, Milvus will filter out the duplicated entities with the same pk while search and query.

It's recommanded to set the pk with dup value to NON-PK fields, for example fields "a", and use auto_id as pk field(or just provide unique auto-increase pk), in this way you could get all the data with pk 1 through exprssions like "a in [1]"

**Comment by zhongJY1998** [comment]
However, I now encounter a problem: For example, there are 10 pieces of data. I set limit10, but only 3 pieces are returned to me. I cannot get all the data with the same data in the same field.
