### ISSUE TITLE
[Bug]: Support python3.12

### ISSUE THREAD

**Issue by niujianya** [milvus-io/pymilvus#1746]
local python version is 3.12.0

**pip3 install pymilvus==2.2.15  ERROR:** 

Installing build dependencies ... error
  error: subprocess-exited-with-error
...
...
ModuleNotFoundError: No module named 'distutils'
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by niujianya** [comment]
i know the reason, when i swicth python3.9, it can be work...
so, high version python is not compatible in some module

**Comment by XuanYang-cn** [comment]
we should check pymilvus installation on python3.12
/assign

**Comment by jamesbuddrige** [comment]
PyMilvus does **not** support Python 3.12 as of 2.3.3. This is due to grpcio dependency being capped at 1.58.0, grpcio support for Python 3.12 is only available on [grpcio 1.59.0+](https://github.com/grpc/grpc/releases/tag/v1.59.0)

**Comment by jamesbuddrige** [comment]
#https://github.com/grpc/grpc/releases/tag/v1.59.0

**Comment by tianyax** [comment]
@niujianya you can fix this by installing `setuptools >=60.0.0`, but, installing grpcio in `Pyhton3.12` still requires `>=1.59`. I've solved the problem by cloning the code and modifying the dependencies, just temporary...

@XuanYang-cn Is there any plan to support `Python3.12` version?

**Comment by XuanYang-cn** [comment]
@tianyax will support on pymilvus 2.3.6 & pymilvus 2.4.0

**Comment by XuanYang-cn** [comment]
close for done
