### ISSUE TITLE
[QUESTION]:  Failed to load data to Milvus: <DataNotMatchException: (code=1, message=The data type of field id doesn't match, expected: INT64, got FLOAT_VECTOR)>

### ISSUE THREAD

**Issue by allisonyang123** [milvus-io/pymilvus#1762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

What is your question?
in  milvus2.3.1 or milvus2.3.2
field1 = FieldSchema(name="id", dtype=DataType.INT64,descrition="INT64", is_primary=True)
field2 = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, descrition="float vector",
                                     dim=2, is_primary=False)
schema = CollectionSchema(fields=[field1, field2], description="collection description")
self.collection = Collection(name=collection_name, schema=schema)
data = [
     [i for i in range(5)],
     [[random.random() for _ in range(2)] for _ in range(5)]
  ]
self.create_collection(collection_name)
mr = self.collection.insert(data)   #but expected:  Failed to load data to Milvus: <DataNotMatchException: (code=1, message=The data type of field id doesn't match, expected: INT64, got FLOAT_VECTOR)>

the data is :   [[1, 2, 3, 4, 5], [[0.3105158465744252, 0.8950156625546624], [0.9155976781469098, 0.21200714091752015], [0.39462295337332065, 0.5530498334145851], [0.33832125406240476, 0.04104237653554721], [0.3758661561451232, 0.46768507654917046]]]

### Anything else?

  Please help me

**Comment by SimFG** [comment]
What is the specific content of the `create_collection` method?

```python
self.create_collection(collection_name)
```

And is the collection firstly created?

**Comment by allisonyang123** [comment]
yes,it is. here are the full create_collection  method. it has been created before insert(data),

`def create_collection(self, collection_name):
        # Create milvus collection if not exists
        try:
            if not self.has_collection(collection_name):
                field1 = FieldSchema(name="id", dtype=DataType.INT64, descrition="INT64", is_primary=True)               
                field2 = FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, descrition="float vector",
                                     dim=2, is_primary=False)            
                schema = CollectionSchema(fields=[field1, field2], description="collection description")              
                self.collection = Collection(name=collection_name, schema=schema)
                LOGGER.info(f"Create Milvus collection: {collection_name}")
            else:
                self.set_collection(collection_name)
            return "OK"
        except Exception as e:
            raise Exception(f"Failed to create_collection: {e}")

    def insert(self, collection_name, vectors):
        # Batch insert vectors to milvus collection
        try:
            self.create_collection(collection_name)
            data = [vectors]
            
            mr = self.collection.insert(data)
            #ids = mr.primary_keys
            
            LOGGER.info(
                    f"Insert vectors to Milvus in collection: {collection_name} with {len(vectors)} rows")
            return 1
        except Exception as e:
            LOGGER.error(f"Failed to insert data to Milvus: {e}")
            raise Exception(f"Failed to insert data to Milvus: {e}")
`

**Comment by allisonyang123** [comment]
thanks for [SimFG].
your comment has inspired me.
I could  find the problem.  because the code of  ` data = [vectors] ` in the insert method don't need additional ` []` . 
when i modify to ` data = vectors ` ，the  error  disappeared.
