### ISSUE TITLE
[Bug]: 示例中search方法的limit没能限制返回数

### ISSUE THREAD

**Issue by liang09255** [milvus-io/pymilvus#1781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

代码中limit=3，但总共返回了六条数据

![image](https://github.com/milvus-io/pymilvus/assets/81953796/9164d1c3-e099-486b-b8ec-69a268f1bd98)

这段代码是官方示例中的[hello_milvus.py](https://raw.githubusercontent.com/milvus-io/pymilvus/master/examples/hello_milvus.py)

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory): CPU
- Method of installation (Docker, or from source): Docker
- Milvus version (v0.3.1, or v0.4.0): v2.3.3  pymilvus: v2.3.3
```

**Comment by XuanYang-cn** [comment]
@liang09255 The TOTAL results number should be `nq * limit`. Its 6 because we searched 2 vectors, limit to 3 each, resulting 2*3=6.

You can see from the double for loop where we print the results
![image](https://github.com/milvus-io/pymilvus/assets/51370125/8bdc8e90-aa17-4162-92df-05d3508a2b20)

**Comment by liang09255** [comment]
Thanks!
