### ISSUE TITLE
 AttributeError: module 'pymilvus.orm.utility' has no attribute 'bulk_load'

### ISSUE THREAD

**Issue by shrijayan** [milvus-io/pymilvus#1789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I run code from https://milvus.io/docs/import_data.md#:~:text=from%20pymilvus%20import%20utility%0Atasks%20%3D%20utility.bulk_load(%0A%20%20%20%20collection_name%3D%22book%22%2C%0A%20%20%20%20is_row_based%3DFalse%2C%0A%20%20%20%20files%3D%5B%22columns.json%22%2C%20%22book_intro.npy%22%5D%0A)

```
from pymilvus import utility
tasks = utility.bulk_load(
    collection_name="book",
    is_row_based=False,
    files=["columns.json", "book_intro.npy"]
)
```

**Comment by SimFG** [comment]
The `utility.bulk_load` seem be deleted or it's a document error, now there is a `utility.do_bulk_insert`. And the example usage of `utility.do_bulk_insert`: https://github.com/milvus-io/pymilvus/blob/master/examples/example_bulkinsert_numpy.py

**Comment by shrijayan** [comment]
> The `utility.bulk_load` seem be deleted or it's a document error, now there is a `utility.do_bulk_insert`. And the example usage of `utility.do_bulk_insert`: https://github.com/milvus-io/pymilvus/blob/master/examples/example_bulkinsert_numpy.py

Thank you! Yesterday just found out, from the docs by searching the term bulk.

Do you have any idea about importing JSON files to Milvus?

**Comment by SimFG** [comment]
this is another example about the `json`, https://github.com/milvus-io/pymilvus/blob/master/examples/example_bulkinsert_json.py
