### ISSUE TITLE
[Bug]: When incorrect tokens are entered, Milvus will continuously attempt to reconnect.

### ISSUE THREAD

**Issue by junjiejiangjjj** [milvus-io/pymilvus#1801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/milvus-io/pymilvus/assets/14136703/3bb91c76-1e00-4ace-a99a-538063b3e365)

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by junjiejiangjjj** [comment]
pymilvus=2.3.1

**Comment by PowderLi** [comment]
duplicated: #1629

please upgrade your milvus rather than pymilvus
you can found more from milvus PR
- [2.3 branch #28437](https://github.com/milvus-io/milvus/pull/28437)
- [master branch #28033](https://github.com/milvus-io/milvus/pull/28033)

**Comment by junjiejiangjjj** [comment]
timeout参数设置也没生效
