### ISSUE TITLE
[Bug]: Exceptions cannot be thrown with Milvus 2.2.x

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/pymilvus#1804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

2.2.x milvus thown exception with old error code:
![img_v3_025n_34667692-87e0-4c37-b51e-be897da57d6g](https://github.com/milvus-io/pymilvus/assets/42060877/03eaa705-58c5-48e1-99c2-1b9fc5a6bbb4)
 While pymilvus didn't handle it:
![img_v3_025n_f78de676-1055-43a9-908f-bc575fba64ag](https://github.com/milvus-io/pymilvus/assets/42060877/b8aa6e7d-6c94-4774-bc40-a2ad59e5985f)

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
close for done
