### ISSUE TITLE
[Bug]: Typeissue in orm/schema.py- Incorrect type for X and Y in check_insert_data_schema()

### ISSUE THREAD

**Issue by vikramsubramanian** [milvus-io/pymilvus#1806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I ran into this error- 

```
  File "<MYSCRIPT'S PATH>", line 44, in insert_item
    collection.insert(emb)
  File "/opt/homebrew/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 490, in insert
    check_insert_data_schema(self._schema, data)
  File "/opt/homebrew/lib/python3.10/site-packages/pymilvus/orm/schema.py", line 330, in check_insert_data_schema
    raise DataNotMatchException(message=f"The data type of field {y.name} doesn't match, expected: {y.dtype.name}, got {x.dtype.name}")
AttributeError: 'int' object has no attribute 'name'
```

### Expected Behavior

AttributeError should not be thrown. Int and any other python type doesn't have .name param. X and Y therefore cannot be of base python type

### Steps/Code To Reproduce behavior

Frustratingly, I don't know...

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory): MacOS Sonoma, m1 max, 16gigs
- Method of installation (Docker, or from source): Docker
- Milvus version (v0.3.1, or v0.4.0): 
- Milvus configuration (Settings you made in `server_config.yaml`): 
```

**Comment by XuanYang-cn** [comment]
@vikramsubramanian This has been fixed https://github.com/milvus-io/pymilvus/issues/1324 please upgrade you pymilvus.

Let me know if its still a problem in the latest pymilvus.
