### ISSUE TITLE
[Bug]: enable reduce_stop_for_best for iterator

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/pymilvus#1830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the past, without using reduce_stop_for_best, iterator may get incorrect results from query node due to duplicated ids, which result in iteration ending ahead

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
close for done
