### ISSUE TITLE
[Bug]: The functionality of the alias link is not working.

### ISSUE THREAD

**Issue by AnthonyTsu1984** [milvus-io/pymilvus#1850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I call `add_connection()` to add connections to Zilliz Cloud clusters, the following are identified:
- Not clear about valid fields in the connection dictionary: Can I add `token`, `user`, `password` in the dictionary?
  
  - Case 1: Include `token` in the alias definition
     
      ```python
      connections.add_connection(
          default={"host": "localhost", "port": 19530},
          dev2={ 
            "uri": "https://in01-**********.aws-us-west-2.vectordb.zillizcloud.com:19530", 
            "token": "db_admin:***"
          },
      )
    
      connections.connect(alias="dev2")
    
      # MilvusException: <MilvusException: (code=2, message=Fail connecting to server on in01-*********.aws-us-west-2.vectordb.zillizcloud.com:19530. Timeout)>
      ```

  - Case 2: Exclude `token` in the alias definition

      ```python
      connections.add_connection(
          default={"host": "localhost", "port": 19530},
          dev2={ 
            "uri": "https://in01-**********.aws-us-west-2.vectordb.zillizcloud.com:19530"
          },
      )
    
      connections.connect(
          alias="dev2",
          token="*******"
       )
    
      # MilvusException: <MilvusException: (code=2, message=Fail connecting to server on in01-*********.aws-us-west-2.vectordb.zillizcloud.com:19530. Timeout)>
      ```

  - Case 3: Use `user` and `password` instead

      ```python
      connections.add_connection(
          default={"host": "localhost", "port": 19530},
          dev2={ 
            "uri": "https://in01-**********.aws-us-west-2.vectordb.zillizcloud.com:19530"
          },
      )
    
      connections.connect(
          alias="dev2",
          user="db-*****",
          password="******"
       )
    
      # MilvusException: <MilvusException: (code=2, message=Fail connecting to server on in01-*********.aws-us-west-2.vectordb.zillizcloud.com:19530. Timeout)>
      ```

- After setting `uri` to an endpoint URI without a trailing port number (i.e. the endpoint URI of any serverless cluster), pymilvus automatically adds 19530 to the end of the specified endpoint, resulting in timeout failure.
  
  When I initiate a connection using the alias added above as follows:

  ```python
    connections.add_connection(
       default={"host": "localhost", "port": 19530},
       dev2={ 
          "uri": "https://in01-**********.aws-us-west-2.vectordb.zillizcloud.com", 
           token": "db_admin:***"
        },
    )

  connections.connection(alias="dev2")
  ```

  The following error occurs:

  ```python
  MilvusException: <MilvusException: (code=2, message=Fail connecting to server on in01-*********.aws-us-west-2.vectordb.zillizcloud.com:19530. Timeout)>
  ```

### Expected Behavior

All the above cases should work instead of throwing timeout errors.

### Environment details

```markdown
- Hardware/Software conditions (OS, CPU, GPU, Memory):

  Mac OS, Apple M1, No GPU, 8G

- Method of installation (Docker, or from source):

  Docker Compose

- Milvus version (v0.3.1, or v0.4.0):

  v2.3.3

- PyMilvus version

  v2.3.4
```

**Comment by xiaocai2333** [comment]
@AnthonyTsu1984 Do you have a way to connect successfully?

**Comment by xiaocai2333** [comment]
For cloud services, there is indeed a bug for adding a connection and then connect. and I will fix it.
You can connect your Milvus as follows:
```
# 1.
connections.connect(
    uri="https://in01-**********.aws-us-west-2.vectordb.zillizcloud.com:19530",
    user="your_user",
    password="your_password"
)
# 2.
connections.connect(
    uri="https://in01-**********.aws-us-west-2.vectordb.zillizcloud.com:19530",
    token="your_user:your_password"
)
# 3.
connections.connect(
    uri="https://in01-**********.aws-us-west-2.vectordb.zillizcloud.com:19530",
    token="your api-key"
)
#4.
connections.connect(
    host="in01-**********.aws-us-west-2.vectordb.zillizcloud.com:19530",
    port="19530",
    secure=True,
    user='your_user',
    password='your_password'
)
```

**Comment by xiaocai2333** [comment]
/assign @AnthonyTsu1984 
By the way.
`add_connection` only supports adding a link first and does not store your token. So the first method you listed is not supported.
You need to specify your token or user password when creating a connection rather than adding a connection.

**Comment by AnthonyTsu1984** [comment]
> /assign @AnthonyTsu1984 By the way. `add_connection` only supports adding a link first and does not store your token. So the first method you listed is not supported. You need to specify your token or user password when creating a connection rather than adding a connection.

Does that mean I cannot include `token`, `user`, and `password` in the alias definition when calling `add_connection()`?

**Comment by xiaocai2333** [comment]
> /assign @xiaocai2333
> 
> > /assign @AnthonyTsu1984 By the way. `add_connection` only supports adding a link first and does not store your token. So the first method you listed is not supported. You need to specify your token or user password when creating a connection rather than adding a connection.
> 
> Does that mean I cannot include `token`, `user`, and `password` in the alias definition when calling `add_connection()`?

yeah，only uri or address.

**Comment by xiaocai2333** [comment]
@AnthonyTsu1984 
It has been fixed, please verify.

**Comment by XuanYang-cn** [comment]
@AnthonyTsu1984 I believe this has been fixed, feel free to reopen this issue if this bug reproduced again
