### ISSUE TITLE
[BUG]insert  Data cannot be inserted

### ISSUE THREAD

**Issue by sunshineyg2018** [milvus-io/pymilvus#188]
RT

**Comment by sunshineyg2018** [comment]
使用文档里面的数据 无法插入向量数据

**Comment by JinHai-CN** [comment]
Please following the issue template to provide environment / platform / milvus info.

**Comment by sunshineyg2018** [comment]
> 请提供环境/平台/环境信息。

python3.7, Milvus version ==0.7.1  ,Recommended pymilvus version==0.2.9

**Comment by sunshineyg2018** [comment]
vectors = [[random.random() for _ in range(128)] for _ in range(1)]
 client.insert(collection_name='test01', records=vectors)

return (Status(code=0, message='Success'), TableInfo(count: 0, partitions_stat: [PartitionStat(tag: '_default', count: 0, segments_stat: [])]))

**Comment by BossZou** [comment]
@sunshineyg2018 You can invoke like this:
```
vectors = [[random.random() for _ in range(128)] for _ in range(1)]
status, _ = client.insert(collection_name='test01', records=vectors)
print("Insert done: ", status)
```
to check the reason data insert fail.

**Comment by BossZou** [comment]
@sunshineyg2018 Try to invoke `flush()` after `insert()`:
```
client.insert(collection_name='test01', records=vectors)
client.flush(['test01'])
```

**Comment by sunshineyg2018** [comment]
status:Insert done:  Status(code=7, message='The vector dimension must be equal to the table dimension.')


I think I know the problem

**Comment by BossZou** [comment]
> status:Insert done: Status(code=7, message='The vector dimension must be equal to the table dimension.')
> 
> I think I know the problem

You can invoke `describe_collection(test01)` to get collection information, in which you can find the value of dimension defined in this collection. If the dimension of inserted vectors is not equal to that defined in this collection, you will receive incorrect information like `he vector dimension must be equal to the table dimension`
