### ISSUE TITLE
[FEATURE] Add hybrid API

### ISSUE THREAD

**Issue by BossZou** [milvus-io/pymilvus#193]
The hybrid APIs allow users to use scalar data in milvus.

Delveop repo: https://github.com/BossZou/pymilvus
Branch: hybrid-dev
example: [example](https://github.com/BossZou/pymilvus/blob/hybrid-dev/examples/example_hybrid.py)

**Comment by BossZou** [comment]
** Create hybrid collection **
* API: 
      `create_hybrid_collection(collection_name, collection_fields)`
* example:
```
collection_fields = [
        {"field_name": "A", "data_type": DataType.INT64},
        {"field_name": "B", "data_type": DataType.INT64},
        {"field_name": "C", "data_type": DataType.INT64},
        {"field_name": "Vec", "dimension": 128, "extra_params": {"index_file_size": 100, "metric_type": MetricType.L2}}
    ]
    status = milvus.create_hybrid_collection(collection_name, collection_fields)
```

**Comment by BossZou** [comment]
** Insert hybrid data **
   * API:
         `insert_hybrid(collection_name, hybrid_entities, vector_entities, ids=None, partition_tag=None, params=None)`

   * example:
```
A_list = [random.randint(0, 255) for _ in range(num)]
    vec = [[random.random() for _ in range(128)] for _ in range(num)]
    hybrid_entities = [
        {"field_name": "A", "field_values": A_list},
        {"field_name": "B", "field_values": A_list},
        {"field_name": "C", "field_values": A_list},
    ]
    vector_entities = [
        {"field_name": "Vec", "field_values": vec}
    ]
    status, ids = milvus.insert_hybrid(collection_name, hybrid_entities, vector_entities)
```

**Comment by BossZou** [comment]
** Hybrid search **
There are four tips to express the relation of search condition:
    * must: All conditions are met at the same time
    * must_not: All conditions are not met at the same time
    * should: one or more of conditions are met 

We support several search condition:
* term: data of specified field is contained in search values. required keys:
    - values
    - boost (supported in the future)

* range: required keys:
    - ranges
    - boost (supported in the future)

    * Supported range type:
        - LT       # less than
        - LTE     # less than or equal
        - EQ      # equal
        - GT      # greater than
        - GTE    # greater than or equal
        - NE       # not equal

* vector:
    - topk:
    - query: query vectors
    - params:


* API:
      `search_hybrid(self, collection_name, query_entities, partition_tags=None, params=None, **kwargs)`

* example:
```
query_hybrid = {
        "bool": {
            "must": [
                {
                    "term": {
                        "A": {"values": [1, 2, 5]}
                    }
                },
                {
                    "range": {
                        "B": {"ranges": {RangeType.GT: 1, RangeType.LT: 100}}
                    }
                },
                {
                    "vector": {
                        "Vec": {"topk": 10, "query": vec[: 10], "params": {"nprobe": 10}}
                    }
                }
            ],
            "should": [
                {
                    "term": {
                        "C": {"values": [33, 40]}
                    }
                },
                {
                    "vector": {
                        "Vec": {"topk": 1, "query": vec[10: 12], "params": {"nprobe": 1}}
                    }
                }
            ]
        }
    }
    status, results = milvus.search_hybrid(collection_name, query_hybrid)
```

**Comment by scsven** [comment]
Done.
