### ISSUE TITLE
[Bug]: [milvus_client] The result is empty for describe_role

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The result is empty for describe_role:
```
client.create_role(role_name="read_only")
>>> client.describe_role(role_name="read_only")
[]
```

### Expected Behavior

Show the role info

### Steps/Code To Reproduce behavior

```markdown
from pymilvus import MilvusClient

# 1. Create a milvus client
client = MilvusClient()

# 2. Create a role
client.create_role(role_name="read_only")

# 3. Describe the role
client.describe_role(role_name="read_only")
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240222-16b4c9a7
- pymilvus version: 2.4.0rc35
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by yiwen92** [comment]
Case 1:
for describe a role with one privilege 
[
     {
         "object_type": "Collection",
         "object_name": "*",
         "db_name": "default",
         "role_name": "db_ro",
         "privilege": "GetLoadState",
         "grantor_name": "zcloud_root"
     }
]
-----
Case 2:
for describe a role with no privilege 
[ 
     { 
       "role_name":"read_only",
        "privilege":""
     }
]

----
Case 3:
for non-exist describe role name
Error: error_msg = "not found the role, maybe the role isn't existed or internal system error"

**Comment by binbinlv** [comment]
Verified and fixed:
pymilvus: 2.4.0rc44

results:
1. for role without privileges:
```
>>> client.create_role(role_name="read_only")
>>> client.describe_role(role_name="read_only")
{'role': 'read_only', 'privileges': []}
```

2. for role with privileges:
```
 >>> client.describe_role(role_name="read_only")
{'role': 'read_only', 'privileges': [{'object_type': 'Collection', 'object_name': '*', 'db_name': 'default', 'role_name': 'read_only', 'privilege': 'GetLoadState', 'grantor_name': 'root'}]}
```

3. for not exist role:
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=not found the role, maybe the role isn't existed or internal system error)>
```
