### ISSUE TITLE
[BUG]Pymilvus connection slows down under gevent

### ISSUE THREAD

**Issue by sml2h3** [milvus-io/pymilvus#194]
**Describe the bug**
Pymilvus connection slows down under gevent,even timeout
**Steps/Code to reproduce behavior**
**gunicorn + flask + pymilvus**

**gunicorn worker_classes**: gevent

`param = {'host': _HOST, 'port': _PORT}
    status = milvus.connect(**param)`

**Expected behavior**

**Environment details**
Pymilvus 

**Screenshots**

**Additional context**
Add the following code to your main program：
`from grpc.experimental.gevent import init_gevent
from gevent import monkey
monkey.patch_all()
init_gevent()`

**Comment by BossZou** [comment]
In the next version, we will remove `connect()`, which may be improve your procedure quality.

**Comment by meton-robean** [comment]
I met this situation!  under {gunicorn + flask + pymilvus}, it took me 23 seconds to connect to Milvus server each time when I ran flask app with gevent mode.  It seems that Milvus(uri=milvus_url) api does not support gevent well~

**Comment by meton-robean** [comment]
> In the next version, we will remove `connect()`, which may be improve your procedure quality.

I met this situation! under {gunicorn + flask + pymilvus}, it took me 23 seconds to connect to Milvus server each time when I ran flask app with gevent mode. It seems that Milvus(uri=milvus_url) api does not support gevent well~

**Comment by szc11121** [comment]
I met this situation too, also gunicorn + flask + pymilvus, but if you change worker class from gevent to eventlet, problems resolved. but ! it took 500ms to search compare to 5ms when just using flask+pymilvus

**Comment by joengzoeksi24** [comment]
> I met this situation too, also gunicorn + flask + pymilvus, but if you change worker class from gevent to eventlet, problems resolved. but ! it took 500ms to search compare to 5ms when just using flask+pymilvus

I use gthread as worker class  instead, it seems ok

**Comment by BossZou** [comment]
You may refer to issue #418
