### ISSUE TITLE
[Bug]: `server_pem_path` is not working without `server_name` when using `connect()`

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/pymilvus#1962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`server_pem_path` is not working without `server_name` when using `connect()`

both these 2 params should be working alone.

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
/unassign
/assign @haorenfsa 
Please help verify

**Comment by haorenfsa** [comment]
verified!
