### ISSUE TITLE
[Bug]: Confused recommended milvus version

### ISSUE THREAD

**Issue by xige-16** [milvus-io/pymilvus#1974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The milvus version recommended in the readme and doc are inconsistent

README：
![image](https://github.com/milvus-io/pymilvus/assets/20124155/2c4f2422-a713-4ea4-8ea8-7b0259b09268)

DOC：
![image](https://github.com/milvus-io/pymilvus/assets/20124155/b2ce638b-fb47-4014-bb1a-8acddf18c00e)

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
should be fixed
