### ISSUE TITLE
[QUESTION]: 请问为什么示例中的dense_index使用L2 metric_type,官方m3模型的示例好像是电积

### ISSUE THREAD

**Issue by seetimee** [milvus-io/pymilvus#2003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

https://github.com/milvus-io/pymilvus/blob/master/examples/hello_hybrid_sparse_dense.py

**Comment by zhengbuqian** [comment]
That is a great question, thanks!

It is a demo to show the usage of hybrid search functionality of Milvus, we paid less attention to the actual model/embedding/metric, so there is no specific reason on the retrieval side we do that.

IP is the only supported metric for sparse vector fields, thus we used L2 for the dense field trying to imply that when using hybrid search you can use arbitrary supported metric type on each field when using RRFRanker.

Based on the [BGE-M3 paper](https://arxiv.org/abs/2402.03216)(section 3.2), IP is the preferred relevance scoring metric type for both dense and sparse embedding of this specific model. So yes the demo is a bit misleading. Do you want to send in a patch? or else I can change it to use IP instead. @seetimee

**Comment by seetimee** [comment]
Please just directly fix it. Thanks a lot for your excellent work.
