### ISSUE TITLE
[Bug]: PlaceHolderValue type is incorrect when input vector is fp16/bf16

### ISSUE THREAD

**Issue by congqixia** [milvus-io/pymilvus#2004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When search with bf16/fp16 vector the place holder type is always binary

### Expected Behavior

Place holder type shall be exactly the input vector type

### Steps/Code To Reproduce behavior

```markdown
See
https://github.com/milvus-io/pymilvus/blob/b9a10c9c41708d4b4d3735d4d1f76713872e31ba/pymilvus/client/prepare.py#L596-L617
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
/unassign
/assign @binbinlv 
Please help verify

**Comment by XuanYang-cn** [comment]
should be fixed
