### ISSUE TITLE
[QUESTION]: Function client.create_index_params() not found

### ISSUE THREAD

**Issue by zhaijunxiao** [milvus-io/pymilvus#2010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

pymilvus version: 2.4.0

I saw examples in the documentation using **client.create_index_params** to create index parameters, 
but I didn't actually find this function.

![image](https://github.com/milvus-io/pymilvus/assets/40786117/0694daf8-a8e8-4261-976b-d34f7cf6abb6)

**Comment by SimFG** [comment]
@zhaijunxiao it's a typo, which should be `prepare_index_params`, reference: https://github.com/milvus-io/pymilvus/blob/master/examples/milvus_client/index.py

**Comment by zhaijunxiao** [comment]
@SimFG thanks. it's work.
