### ISSUE TITLE
[QUESTION]: Is it possible to use `query_iterator` with `MilvusClient`?

### ISSUE THREAD

**Issue by emanueledomingo** [milvus-io/pymilvus#2044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Reading the documentation, it seems that the only way to paginate, using the `MilvusClient` interface is by setting `offset` and `limit` in the `query` method.

Reading the docs, to avoid this complexity we can use `query_iterator` but this seems to be supported only if using the ORM Mode.

### Anything else?

In addition to this, if i follow the example [here](https://milvus.io/docs/with-iterators.md), it does not work:

```py
from pymilvus import MilvusClient

# 1. Set up a Milvus client
client = MilvusClient(
    uri="http://localhost:19530"
)

# 2. Create a collection
client.create_collection(
    collection_name="quick_setup",
    dimension=5,
)

# 3. Insert randomly generated vectors 
colors = ["green", "blue", "yellow", "red", "black", "white", "purple", "pink", "orange", "brown", "grey"]
data = [ {
        "id": i, 
        "vector": [ random.uniform(-1, 1) for _ in range(5) ], 
        "color": random.choice(colors), 
        "tag": random.randint(1000, 9999) 
    } for i in range(10000) ]

for i in data:
    i["color_tag"] = "{}_{}".format(i["color"], i["tag"])

# 4. Insert entities to the collection
res = client.insert(
    collection_name="quick_setup",
    data=data
)

from pymilvus import Collection

# 1. Get the prepared collection
collection = Collection("quick_setup") 
# this raises "ConnectionNotExistException: <ConnectionNotExistException: (code=1, message=should create connect first.)>"
```

**Comment by shell11708** [comment]
You can use client's connection for your collection.

```python
collection = Collection("quick_setup", using=client._using)
```

**Comment by emanueledomingo** [comment]
> In that example, you can use client's connection for your collection.
> 
> ```python
> collection = Collection("quick_setup", using=client._using)
> ```

Thanks for the suggestion!
