### ISSUE TITLE
[Enhancement]: Reduce pymilvus package size

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#2067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

1. remove scipy as depenency
2. make depenencies of bulkwriter optional

**Comment by XuanYang-cn** [comment]
/assign @zhengbuqian 
Please help with the scipy part

**Comment by zhengbuqian** [comment]
/unassign

scipy has been removed from both master and 2.4

**Comment by pedromoraesh** [comment]
Is this update already in pip or only with make?

**Comment by XuanYang-cn** [comment]
> Is this update already in pip or only with make?

Not in pip ye, will be available at pymilvus>=2.4.2
