### ISSUE TITLE
[Bug]: Failed to create sparse vector index

### ISSUE THREAD

**Issue by wyueai** [milvus-io/pymilvus#2100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For the latest 2.4 version, when I tried to create an index on the spare vector field, which dtype = DataType.SPARSE_FLOAT_VECTOR, I received an error message: 

RPC error: [create_index], <MilvusException: (code=1100, message=index type not match: expected=Trie, actual=SPARSE_INVERTED_INDEX: invalid parameter)>, <Time:{'RPC start': '2024-05-20 00:47:10.251044', 'RPC error': '2024-05-20 00:47:10.271028'}>
Failed to create an index on collection

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): 
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by luc42ei** [comment]
what was the solution??
