### ISSUE TITLE
[QUESTION]: 向量的维度只能设置为一个定值吗？能不能设置一个范围？

### ISSUE THREAD

**Issue by zyc1128** [milvus-io/pymilvus#2102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by zhuwenxing** [comment]
Why do vectors have multiple dimensions? Is it because a single model can generate vectors of different dimensions, or because multiple models are used?

**Comment by zyc1128** [comment]
Thanks,I might be a bit of a ditz
