### ISSUE TITLE
删除数据后,再次查询,实体没有及时更新

### ISSUE THREAD

**Issue by zhongJY1998** [milvus-io/pymilvus#2106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

删除数据后,再次查询,实体没有及时更新, 

### Anything else?

我的代码如下
def _delete_data(self, data, collection_name):
        
    try:
        collection = Collection(collection_name) 
        # 如果为空则不进行删除操作, 因为他还没有加载到内存上            
        if not collection.num_entities:
            return
        
        for info in data:
            assert isinstance(info, dict), "input format error, params must is dict."
            for k, v in info.items():
                delete_expr = f"{k} in [\'{v}\']"
                status = collection.delete(expr=delete_expr)
                logging.info(f"delete info: {status}")

        logging.info(f"from collection: {collection_name} delete data successful.")
        logging.info(f"Beforre delete num_entities: {collection.num_entities}")
        def wait_for_compaction(interval=0.5):
            collection.compact()
            while True:
                state = collection.get_compaction_state()
                # ref: https://github.com/milvus-io/pymilvus/blob/master/pymilvus/client/types.py
                if state.state.Completed == 0:
                    logging.info("Compaction failed.")
                    break
                elif state.state.Completed == 1:
                    logging.info("Compaction in progress...")                        
                    time.sleep(interval)
                elif state.state.Completed == 2: 
                    logging.info("Compaction completed.")
                    break
                else:
                    raise NotImplementedError
            collection.flush()

        wait_for_compaction()
        collection.fush()
        collection.load()
        utility.wait_for_loading_complete(collection_name=collection_name)
        logging.info(f"After delete num_entities: {collection.num_entities}")
    except Exception as err:
        logging.error(f"from collection: {collection_name} delete data failed.")
        logging.error(traceback.format_exc())

为什么我打印的logging.info(f"Beforre delete num_entities: {collection.num_entities}") 和 logging.info(f"After delete num_entities: {collection.num_entities}") 结果还是一样额, 有什么办法解决吗?

**Comment by SimFG** [comment]
@zhongJY1998 
num_entity is an approximate number. If you want to get the exact value in real time, you need to use:
```
hello_milvus.query(expr="", output_fields=["count(*)"], consistency_level="Strong")
```

but before executing the query, you need to xi ancreate index and load

refer doc:https://milvus.io/docs/get-and-scalar-query.md#Advanced-operators

**Comment by zhongJY1998** [comment]
谢谢

**Comment by xinmos** [comment]
我现在仍然能复现这个问题：pymilvus==2.5.8

![Image](https://github.com/user-attachments/assets/cfb7a3cf-6b67-467d-ba38-6c63c79447a6)

尽管在 attu 软件中添加了索引并重新 load 数据，查出来的数量仍然不对。

```python
connections.connect(
    db_name='digital_twin',
    address='127.0.0.1:19530'
)
collection = Collection("dev_artwork")

async def main():
    res = collection.query("", output_fields=["count(*)"], consistency_level="Strong")
    print(res) # data: ["{'count(*)': 3}"]

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
实际数量

![Image](https://github.com/user-attachments/assets/728c2f00-01af-441e-9a9c-b9b8116733b7)

![Image](https://github.com/user-attachments/assets/6c184fe9-7ac0-42c1-9135-23329b2af647)

**Comment by SimFG** [comment]
I guess three pk-identical data were inserted, and count * currently does not remove duplicate data.
