### ISSUE TITLE
请问如何判断数据有没有load到内存

### ISSUE THREAD

**Issue by zhongJY1998** [milvus-io/pymilvus#2108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SimFG** [comment]
Does it mean whether the collection is loaded?

**Comment by zhongJY1998** [comment]
是的

**Comment by zhongJY1998** [comment]
因为我想做成服务, 但是第一次调用search的时候我如何判断我的数据有没有被加载到内存, 如果没有被加载我就执行 collection.load()

**Comment by SimFG** [comment]
you can try to use:
```
utility.load_state(collection_name) == LoadState.NotLoad
```

**Comment by zhongJY1998** [comment]
好的,非常感谢. 我还想请教一个问题, 我们昨天沟通的时候,您告诉我 query(expr="", output_fields=["count(*)"], consistency_level="Strong")获取精准的实体数量,但是我发现这个操作非常耗时, 比我正常search还耗时,请问这种情况有什么办法解决吗?

**Comment by zhongJY1998** [comment]
我query需要耗时0.4s 但是我search才耗时0.19s

**Comment by SimFG** [comment]
Yes, because `strong consistency` is set, the exact number will be calculated, so it takes a long time. If you don't need very accurate numbers, you can use num entity

**Comment by zhongJY1998** [comment]
好的,非常感谢
