### ISSUE TITLE
[QUESTION] Rpc error: <_Rendezvous of RPC that terminated with

### ISSUE THREAD

**Issue by Jfxhuangdao** [milvus-io/pymilvus#211]
Rpc error: <_Rendezvous of RPC that terminated with:
 status = StatusCode.UNAVAILABLE
 details = "Transport closed"
 debug_error_string = "{"created":"@1590488128.998782157","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Transport closed","grpc_status":14}"
#----------------------------------------
_HOST = '127.0.0.1'
_PORT = '19530'  # default value
milvus = Milvus(host=_HOST, port=_PORT)
#--------------------------------------------------
pymilvus==0.2.11

**Comment by BossZou** [comment]
@Jfxhuangdao May you provide milvus config file here?
