### ISSUE TITLE
[Bug]: Iterator not handle OR expr operator correctly

### ISSUE THREAD

**Issue by MrPresent-Han** [milvus-io/pymilvus#2113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When expr has OR operator, like a>8 || b < 10, query iterator will wrongly handle the priority of operator because appending AND operator in the tail

### Expected Behavior

related: https://github.com/milvus-io/milvus/issues/33594

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
seems fixex
