### ISSUE TITLE
[Bug]: Can not use poetry to install pymilvus >= 2.4

### ISSUE THREAD

**Issue by Raysilience** [milvus-io/pymilvus#2131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

create a new environment using poetry, execute in terminal `poetry add pymilvus=^2.4.3`, it will raise the following error,
![image](https://github.com/milvus-io/pymilvus/assets/45241093/0331b760-54b3-4c8d-b074-7dfa0ab2a57e)

### Expected Behavior

successfully install pymilvus with poetry 

### Steps/Code To Reproduce behavior

```markdown
1. create a new environment using poetry
2. execute in terminal `poetry add pymilvus=^2.4.3`
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by zhuwenxing** [comment]
@Raysilience 
what is your os system? It works well in my Mac
![image](https://github.com/milvus-io/pymilvus/assets/12268675/7a589570-ba34-4a24-b7cf-c69afd1782ae)

pymilvus 2.3.4 includes a milvus-lite lib, and it is not supported in windows.

**Comment by Raysilience** [comment]
Mine is windows. Then how to exclude the milvus-lite while installing pymilvus.

**Comment by zhuwenxing** [comment]
> @zhuwenxing Mine is windows. Then how to exclude the milvus-lite while installing pymilvus.

@XuanYang-cn @junjiejiangjjj 
any advice?

**Comment by Raysilience** [comment]
@zhuwenxing @XuanYang-cn @junjiejiangjjj  I check the pyproject.toml file. Maintainers list the milvus-lite inside the dependencies that leads to mandatory installation. This will definitely affect the developers operating on windows who are also using poetry to manage their projects. Would you consider moving the milvus-lite to optional dependencies such that windows developers still have access to pymilvus while other users are still able to install milvus-lite via poetry add pymilvus[milvus-lite] i.e. 
[project.optional-dependencies]
milvus-lite = [
  "milvus-lite>=2.4.0",
]
If so, I could create a pr to solve it.

**Comment by XuanYang-cn** [comment]
@Raysilience we want "milvus-lite" to be the default dependency of pymilvus. So "No" for change it to optional dependencies for all platform.

However making it optional for Windows platform ONLY might  be possible. Can you investigate and create a pr for it? I'll do some investigation myself too.

**Comment by Raysilience** [comment]
@XuanYang-cn Sure, I find out that poetry supports environment marker which might be suitable for the current case. I will give it a try, and if it works I will create a pr

**Comment by XuanYang-cn** [comment]
https://github.com/milvus-io/pymilvus/pull/2136 This PR will add checks for windows platform for every PR.

**Comment by XuanYang-cn** [comment]
Should be ready in pymilvus==2.4.4
/assign @Raysilience 
/unassign
