### ISSUE TITLE
[QUESTION]: How to set a token that never expires?

### ISSUE THREAD

**Issue by aboutmydreams** [milvus-io/pymilvus#2145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

How to set a token that never expires? 

I see lots of usecase that connect milvus use milvus api key, but I can't find how to set it in the pymilvus code.

**Comment by XuanYang-cn** [comment]
@aboutmydreams What do you mean by saying "never expires"? Once a token is created, it can always be used to conncet with Milvus/ZillizCloud unless the Admin deleted or expired the token. 

Are you using Milvus or ZillizCloud?
