### ISSUE TITLE
[QUESTION]: Bulk insert supports uploading local files directly to S3

### ISSUE THREAD

**Issue by OxalisCu** [milvus-io/pymilvus#2160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Currently, the bulk insert function of pymilvus supports using remote_writer to generate data files (parquet, json, etc.) and upload them to s3, which requires schema verification and buffer_size verification.

Therefore, if I need to **import data exported from other databases (such as JSON format files) into milvus**, I have to go through the reading, verification and upload process using pymilvus, and if the data file is large, performance problems will occur.

**My question is, is it planned to support not verifying the files, directly uploading the files to s3 through the local file path, and then importing them into milvus?**

For example, by rewriting the _upload method of remote_writer, it is possible to directly upload files through local paths.

If you don't plan to support it, why? Is there any way to easily import large amounts of data?

### Anything else?

nothing

**Comment by OxalisCu** [comment]
In addition, is there a way to import data files (parquet, json, etc.) directly into milvus without going through any client (pymilvus)?

**Comment by bigsheeper** [comment]
> In addition, is there a way to import data files (parquet, json, etc.) directly into milvus without going through any client (pymilvus)?

We recommend using the RESTful API: https://milvus.io/api-reference/restful/v2.4.x/v2/Import%20(v2)/Create.md
Actually, you can upload files to S3 yourself and then directly call the RESTful API. Milvus does not mandate the use of remote_writer.

**Comment by OxalisCu** [comment]
Thanks for your answer, I will close this issue

**Comment by OxalisCu** [comment]
Thanks for your answer, I will close this issue
