### ISSUE TITLE
[Bug]: Use Furthest Neighbor Search

### ISSUE THREAD

**Issue by RaphaelCanin** [milvus-io/pymilvus#2185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't find anywhere in the doc a way to use the feature from [PR#27452](https://github.com/milvus-io/milvus/pull/27452) in the main repo.

### Expected Behavior

I expect to have a way to use this feature.

### Environment details

```markdown
Local run using pymilvus 2.4.4 on Ubuntu 22.04 and Python 3.10.12
```

### Anything else?

Thank's a lot for your work, milvus is an incredible tool

**Comment by XuanYang-cn** [comment]
Seems answered here https://github.com/milvus-io/milvus/issues/27451#issuecomment-2239383993
closing this issue
