### ISSUE TITLE
[Bug]: Milvus 连接错误: <_InactiveRpcError of RPC that terminated with: 	status = StatusCode.UNAUTHENTICATED 	details = "missing authorization in header" 	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"missing authorization in header", grpc_status:16, created_time:"2024-07-31T14:52:52.605898+08:00"}" >

### ISSUE THREAD

**Issue by Jerryyyy0** [milvus-io/pymilvus#2206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

当我在操纵pymilvus时就报这个错
Milvus 连接错误: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "missing authorization in header"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"missing authorization in header", grpc_status:16, created_time:"2024-07-31T14:52:52.605898+08:00"}"
>

### Expected Behavior

当我在操纵pymilvus时就报这个错

### Steps/Code To Reproduce behavior

```markdown
def createCollectionAndInsertRecords(self, collection_name, partition_name, data_list):
        try:
            with get_milvus_client():
                # 检查连接是否存在
                if not connections.has_connection("default"):
                    logging.info("Connection to Milvus failed.")
                else:
                    logging.info("Successfully connected to Milvus.")

                # 创建集合 schema
                if collection_name in list_collections():
                    collection = Collection(name=collection_name)
                else:
                    schema = CollectionSchema(self.fields, description="example collection")
                    collection = Collection(name=collection_name, schema=schema)
                    index = {"index_type": "IVF_FLAT", "params": {"nlist": 128}, "metric_type": "L2"}
                    if not collection.has_index():
                        collection.create_index("doc_section", index)
                    collection.load()
                partition = Partition(collection, name=partition_name)
                res = partition.insert(data_list)
                count = res.insert_count
                logging.info(f"-------------成功添加{count}条记录到向量库-------------")
                return True
        except Exception as e:
            logging.error(f"存储文本内容到milvus失败: {e}")
            return False
```

### Environment details

```markdown
- cpu
- Method of installation (Docker):
- Milvus version (2.3.20):
- pymilvus:2.3.7
```

### Anything else?

当我在操纵pymilvus时就报这个错
Milvus 连接错误: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "missing authorization in header"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"missing authorization in header", grpc_status:16, created_time:"2024-07-31T14:52:52.605898+08:00"}"
>

**Comment by Jerryyyy0** [comment]
我已经配置了milvus用户名和密码
同时在docker的milvus.yml中配置了
security:
    authorizationEnabled: true
    # The superusers will ignore some system check processes,
    # like the old password verification when updating the credential
    superUsers: root
    tlsMode: 0

**Comment by SimFG** [comment]
can you show the `get_milvus_client` method detail?

**Comment by Jerryyyy0** [comment]
from contextlib import contextmanager

from pymilvus import connections, utility

# 创建 Milvus 连接
from app.config import globalAppSettings
from app.utils.SM4Util import decrypt

connections.connect(
    alias="default",
    host=decrypt(globalAppSettings.milvus_host),
    port=decrypt(globalAppSettings.milvus_port),
    user=decrypt(globalAppSettings.milvus_username),
    password=decrypt(globalAppSettings.milvus_password),
    # user='',
    # password='',
    token='root:Flzxsqc@112890',
    secure=False  # 如果使用HTTPS，请设置为True
)


@contextmanager
def get_milvus_client():
    """上下文管理器，用于处理 Milvus 客户端的连接"""
    try:
        yield connections.connect("default")
    except Exception as e:
        logging.error(f"Milvus 连接错误: {e}")
        raise e

**Comment by Jerryyyy0** [comment]
from contextlib import contextmanager

from pymilvus import connections, utility

# 创建 Milvus 连接
from app.config import globalAppSettings
from app.utils.SM4Util import decrypt

connections.connect(
    alias="default",
    host=decrypt(globalAppSettings.milvus_host),
    port=decrypt(globalAppSettings.milvus_port),
    user=decrypt(globalAppSettings.milvus_username),
    password=decrypt(globalAppSettings.milvus_password),
    secure=False  # 如果使用HTTPS，请设置为True
)


@contextmanager
def get_milvus_client():
    """上下文管理器，用于处理 Milvus 客户端的连接"""
    try:
        yield connections.connect("default")
    except Exception as e:
        logging.error(f"Milvus 连接错误: {e}")
        raise e

**Comment by Jerryyyy0** [comment]
I found the error's reason, thank you

**Comment by XuanYang-cn** [comment]
/close
for fixed
