### ISSUE TITLE
[Bug]: Pymilvus 2.4.5 depends on numpy <1.25.0

### ISSUE THREAD

**Issue by Elijas** [milvus-io/pymilvus#2236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

pymilvus (2.4.5) depends on numpy (<1.25.0)
opencv-python (4.10.0.84) depends on numpy (>=1.26.0)

I can't install opencv-python because pymilvus is using old version of numpy

### Expected Behavior

pymilvus should be compatible with new numpy versions

### Steps/Code To Reproduce behavior

```markdown
pip install pymilvus@2.4.5
pip install opencv-python@4.10.0.84
```

### Environment details

```markdown
Python 3.11.4
```

### Other details

Temporary workaround
```
pip install opencv-python@4.8.1.78
```

**Comment by XuanYang-cn** [comment]
@Elijas `"numpy<1.25.0;python_version<='3.8'",` Means numpy version for python3.8 ONLY. numpy is not restricted  for python > 3.8.

To solve the problem, you could try to upgrade python version to like 3.11

**Comment by Elijas** [comment]
Updated `>=3.8` to `>=3.11`
in
pyproject.toml
```
[tool.poetry.dependencies]
python = "<3.13,>=3.11"
```
this fixed the issue, thanks!
