### ISSUE TITLE
[FEATURE]: Do we need to require an upper limit version of grpc?

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/pymilvus#2237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

https://github.com/milvus-io/milvus/issues/35667

I'm thinking of we can directly use grpc >= 1.49.1 but don't set the upper limit

**Comment by XuanYang-cn** [comment]
I tested the latest grpcio, it works perfectly. I think we can loose the upper limit of grpcio in the next version.
