### ISSUE TITLE
[QUESTION] Change collection/partition parameters after it's created

### ISSUE THREAD

**Issue by drakerc** [milvus-io/pymilvus#226]
**What is your question?**
Hi, thanks for your work on Milvus, it works really well.
I'm wondering: is it possible to change some collection parameters after it's created? For example, let's say that I've created a collection with too small `index_file_size`, filled it with vectors and then decided to change it. 
Is it possible? If not, what would be the solution here if I don't want to lose the stored vectors in this collection? I guess the brute-force solution would be to create a new collection and then search all vectors in the old collection and insert all of them into the new one (however, how would I fetch all stored vectors? I guess I could use the `.search` method, but it requires me to enter `query_records`, but I want all of them)

And the second question is similar, but about partitions. Is it possible to move/copy inserted vectors into another partition?
For example, let's say that I have inserted about 200000 vectors into the default collection without any partition (partition `_default`). Then I created a new partition called `test_partition`. How can I move all these vectors from `_default` to `test_partition`?

**Comment by BossZou** [comment]
@drakerc Currently therre is no access to modify collection/partition parameters after created. And if you want to get raw vectors from collection/partition, you are recommended to use API `get_entity_by_id` , see more deatail example [here](https://github.com/milvus-io/pymilvus/tree/master/examples).

**Comment by drakerc** [comment]
Thank you, I'll just use the `get_entity_by_id` for now to get all records and will just put them in a new collection/partition and delete the old one for now.

My last question (I think I know the answer because I haven't found this API endpoint myself, but maybe I'm wrong): Is it possible to use the `search` endpoint to search by entity_id instead of by vectors? 
I want to be able to search for similar vectors by the already stored vectors in the Milvus by their ID.  Because I couldn't find searching by ID, I'm currently using the `get_entity_by_id` endpoint first to get the vectors, and then I use the `search` endpoint with vectors. But I guess if Milvus supported searching by ID, it could be faster and my solution is not optimal?

**Comment by BossZou** [comment]
@drakerc thank you for your suggestion.  Currently we have no API for search-by-id. I may wonder that why you need a API to search by entity-id, or is there a application scenario to search by entity-id instead of vectors?

**Comment by shiyu22** [comment]
Hi drakerc @drakerc ,thank you for using Milvus,  welcome to join our [Slack channel](https://join.slack.com/t/milvusio/shared_invite/enQtNzY1OTQ0NDI3NjMzLWNmYmM1NmNjOTQ5MGI5NDhhYmRhMGU5M2NhNzhhMDMzY2MzNDdlYjM5ODQ5MmE3ODFlYzU3YjJkNmVlNDQ2ZTk), where can connect with other users and contributors.

By the way, welcome to share with us the scene of using milvus.

**Comment by drakerc** [comment]
Thank you, I'll check out the Slack in a few weeks.

Not having a search-by-id is OK for me for now because of the scale (and because it's fast enough  for me to make two queries, first the id query, and then the search-by-vectors), but I guess if Milvus supported it it could be a bit faster/cleaner because it would be just 1 query instead of 2.

I'm using Milvus to store image features vectors (from a ResNet CNN) for image searching and it's really good for this application, fast and precise. I'll think about open-sourcing it in the future.
I have implemented the `search-by-id` because in my case, the application works like this: Users can see a gallery of images (in my case, these are shop products) and they can click one of the images to find similar images (products).
For example, if a user is browsing a red t-shirt, he can click its image (I'm storing the Milvus ID in MySQL for this product) to find similar products (other similar t-shirts) (so he will get a list of similar products or rather products with similar images). 
In order for this to work, I have to first get the vectors of this image's Milvus ID (`get_entity_by_id`) and then I `search` using these vectors. It currently works very well and it's perfectly fast for me :).

**Comment by shiyu22** [comment]
Thanks for sharing, it looks more like a recommendation system. Will this be apply to such a shopping platforms? And can you sheare us your platform?

**Comment by drakerc** [comment]
Correct.
I'm also also using Milvus in another small project that will be publicly available (image searching again) - I'll let you know about it on Slack when I'll have some more information.
In the meantime, I'm closing this issue as resolved, and thank you for information.
