### ISSUE TITLE
[QUESTION] Pagination support?

### ISSUE THREAD

**Issue by drakerc** [milvus-io/pymilvus#227]
**What is your question?**

Is there some kind of a pagination support like in other search engines?
For example, let's say that I want to find top 10 results first (`top_k: 10`). And then want to get more results, after 10 results. Is that possible?

My current solution for this is to just increase the `top_k` value and discard the unneeded results. However, I guess it's not the most efficient (and certainly not clean) way. So for example, if I'm showing top 10 results on the first page, and then the user goes to the second page, I'll set the `top_k` to 20 and return `results[10:]` results, discarding the first ten results, and so on and on...

**Comment by BossZou** [comment]
@drakerc Currently we don't support this situation. So you must to get top 20 results first(`top_k: 20`) then slice the last 10 results
