### ISSUE TITLE
Support insert with string ID

### ISSUE THREAD

**Issue by sunshineyg2018** [milvus-io/pymilvus#228]
milvus.insert(ids="xafsafhioasf15151616163")This form of IDS

**Comment by BossZou** [comment]
@sunshineyg2018 , Currently only integer ids are supported. We plan to support this in the future. See [here](https://github.com/milvus-io/milvus/projects) to get more information.

**Comment by qbzenker** [comment]
+1 for this feature!

**Comment by sibadakesi** [comment]
+1 for this feature!

**Comment by shashi-netra** [comment]
You could hash the id string into an integer as a workaround. MurmurHash3 ("mmh3") is a reliable and fast hashing algo.

**Comment by XuanYang-cn** [comment]
Already available on pymilvus 2.1.0
