### ISSUE TITLE
[QUESTION] A question about list_partitions function's return value

### ISSUE THREAD

**Issue by susoooon** [milvus-io/pymilvus#232]
**What is your question?**
When I use list_partitions,The collection_name  has been specified
Maybe collection_name in return values is not necessary 
![image](https://user-images.githubusercontent.com/40882819/86112055-14191580-bafa-11ea-9657-af0006a40ae4.png)

**Comment by BossZou** [comment]
@susoooon Thank for your seggestion. We will remove collection_name in return values future.

**Comment by scsven** [comment]
Fix in release 0.3.0.
