### ISSUE TITLE
[QUESTION]: Milvus 2.4.15 - pymilvus 2.4.9 Message -> this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server

### ISSUE THREAD

**Issue by cmxela** [milvus-io/pymilvus#2355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

Not sure which is the problem, the versions look like are the adequate. The code I am ussing and is failing is 

```python
from pymilvus import MilvusClient, FieldSchema, CollectionSchema, DataType, Collection, Index

# Connect to Milvus
client = MilvusClient(
    uri="https://milvus.k8s.xxxxxxx.com",
    db_name="default"
)
```

This is milvus standalone deployed on a microk8s single node cluster

the deployment has been done with helm

**Comment by XuanYang-cn** [comment]
This is a misleading message, I'll fix it soon. Actually there's one more possible reason: the port of the uri is incorrect.

@cmxela Please double check your Milvus server's port and attach the correct port into your uri like `http://localhost:19530`

**Comment by XuanYang-cn** [comment]
should be fixed
