### ISSUE TITLE
[QUESTION] - What is the best way to update by ID?

### ISSUE THREAD

**Issue by qbzenker** [milvus-io/pymilvus#239]
**What is your question?**

I'd like to update a vector by `id`. Also, strangely it looks like I can insert multiple vectors with the same `id`. My expectation would be that if I called an `insert` operation with an existing `id`, the vector for that `id` would update, not insert new. It seems like the way to update a vector, is to first delete the vector by id, then insert it fresh. Is this the best / only way? 

Thanks!

**Comment by BossZou** [comment]
@qbzenker Milvus do not support unique id, the reason refer to [here](https://github.com/milvus-io/milvus/issues/2545). Currently the only to update a vector is to delete it then insert new one.

**Comment by qbzenker** [comment]
That makes sense. Thanks and I appreciate your response, @BossZou!
