### ISSUE TITLE
[FEATURE] 并发处理请求

### ISSUE THREAD

**Issue by JackChen20200818** [milvus-io/pymilvus#240]
例如searchnn， 在不同的分区里分别搜topk结果， 只能串行执行，性能很低。 这个完全可以改成并发处理的。 其中没有任何写操作。

**Comment by BossZou** [comment]
@JackChen20200818 , May you invoke search APIs asynchronously? You can refer here: [async example](https://github.com/milvus-io/pymilvus/blob/master/examples/example_async.py)

**Comment by BossZou** [comment]
@JackChen20200818 , you are right. A search request is divided to several search tasks, which corresponding to one vector file. But those tasks  are executed serially. Because each task may use as more as computation resource, executing in parallel
can not improve performance.

**Comment by JackChen20200818** [comment]
谢谢你的答疑。
