### ISSUE TITLE
[BUG] get_entity_by_id return empty result when len(ids) > 1000

### ISSUE THREAD

**Issue by chenjx1005** [milvus-io/pymilvus#241]
**Describe the bug**
```
import milvus
print(milvus.__version__)  # result : 0.2.14
from milvus import Milvus, IndexType, MetricType, Status

milvus = Milvus("127.0.0.1", '19530')
status, f = milvus.get_entity_by_id("HZ_27W_attrV5_512d_vidnet", [207111]* 1000)
status, f2 = milvus.get_entity_by_id("HZ_27W_attrV5_512d_vidnet", [207111]* 1001)

print(len(f))  # result: 1000
print(len(f2))  # result: 0
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**

- Hardware/Softward conditions (CentOS 7, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Comment by BossZou** [comment]
@chenjx1005 , we limit the max of ids is 1000, so if you get more than 1000 vectors one time, server will return errror status:
```
Status(code=5, message='Input id array size cannot exceed: 1000')
```

**Comment by meton-robean** [comment]
> @chenjx1005 , we limit the max of ids is 1000, so if you get more than 1000 vectors one time, server will return errror status:
> 
> ```
> Status(code=5, message='Input id array size cannot exceed: 1000')
> ```

Is the speed of  milvus.get_entity_by_ids() is low? Why does Milvus limit the id array size?

**Comment by BossZou** [comment]
> > @chenjx1005 , we limit the max of ids is 1000, so if you get more than 1000 vectors one time, server will return errror status:
> > ```
> > Status(code=5, message='Input id array size cannot exceed: 1000')
> > ```
> 
> Is the speed of milvus.get_entity_by_ids() is low? Why does Milvus limit the id array size?

You are right. Because 'get_entity_by_ids()' is slow, so we limited the id-array size to avoid having an effect on server quality.

**Comment by BossZou** [comment]
Not active. Close it.
