### ISSUE TITLE
[BUG] when I insert vectors into milvus, I get an error 

### ISSUE THREAD

**Issue by leidaxia** [milvus-io/pymilvus#242]
![image](https://user-images.githubusercontent.com/20982126/91166116-71010880-e704-11ea-8d27-4801d320eb4f.png)

**Comment by BossZou** [comment]
@leidaxia , May you provide more details to help locate problem, source code, os information, milvus server version and python sdk version, or more ?

**Comment by leidaxia** [comment]
1. I use this dockerfile, and deploy it on k8s succefully
![image](https://user-images.githubusercontent.com/20982126/91247517-0512b480-e785-11ea-9851-630c2abb0f02.png)
2.the k8s give me the host and port , and I can telnet them succefully
3.我是一步步按照https://github.com/milvus-io/pymilvus 进行，但是在这一步遇到上面的error，我怀疑是insert的时候报错
![image](https://user-images.githubusercontent.com/20982126/91249231-0cd45800-e789-11ea-8eed-eab0904b4481.png)

**Comment by BossZou** [comment]
Reproduced every time?

**Comment by leidaxia** [comment]
> Reproduced every time?
不是每次都生成的，我按照上面的教程，是先创建collection，然后写入报错的

**Comment by BossZou** [comment]
Did this procedure run well in host machine?

**Comment by BossZou** [comment]
Which milvus server version and sdk version are used?

**Comment by leidaxia** [comment]
> Did this procedure run well in host machine?
YES

**Comment by leidaxia** [comment]
> Which milvus server version and sdk version are used?
![image](https://user-images.githubusercontent.com/20982126/91267934-f806bd00-e7a6-11ea-9f45-c32caa8e5d27.png)
I use dockerfile  to deploy it on k8s
![Uploading image.png…]()

**Comment by BossZou** [comment]
Not active, close it.
