### ISSUE TITLE
Manual index creation

### ISSUE THREAD

**Issue by markoarnauto** [milvus-io/pymilvus#248]
**What is your question?**
Calling `create_index` without `index_file_size` will trigger the index creation neglecting the current size of non-indexed segments (right?). So in case someone wants to handle index creation manually one could call `create_index` without specifying `index_file_size`.

But when creating a collection `index_file_size` has to be set (default 1024). Wouldn't `None` be an appropriate option to indicate that index creation is done manually?

**Comment by BossZou** [comment]
The parameters `index_file_size` is used when creating collection,  you can refer to [milvus index_file_size](https://milvus.io/docs/v0.10.3/performance_faq.md#How-can-I-get-the-best-performance-from-Milvus-through-setting-index_file_size)

**Comment by markoarnauto** [comment]
Ok thanks. So it's rather a `segment_file_size` since collections without indices are possible. What happens when you set `index_file_size` to let's say 1024 when creating the collection. And on the other hand set it to 512 when creating the index?

**Comment by BossZou** [comment]
@markoarnauto ,actually, the parameters `index_file_size` will take effect during merge operation. When creating a index, milvus server could merge segments first then create the index. you can refer to [milvus #3921](https://github.com/milvus-io/milvus/issues/3921)
