### ISSUE TITLE
Is it possible to pull vectors+IDs from a collection once inserted?

### ISSUE THREAD

**Issue by safurrier** [milvus-io/pymilvus#250]
**What is your question?**

If I wanted to clone a collection by first pulling all vectors and associated IDs from a collection would be that be possible to do with pymilvus? Or would I need to duplicate a collection by creating a new collection and inserting the same source vectors+ID pairs used to create the original collection?

If this capability exists is it possible in `pymilvus` < 0.2.10?

**Comment by BossZou** [comment]
@safurrier , in pymilvus < 0.2.10, you can only duplicate a collection to do it.

**Comment by safurrier** [comment]
Got it @BossZou . Is that functionality possible in newer versions of pymilvus?

**Comment by BossZou** [comment]
@safurrier , that functionality could not be added into pymilvus. We'll provide third-party tools to help migrate data in the future.

**Comment by BossZou** [comment]
@safurrier , you may refer to [milvus tools](https://github.com/milvus-io/milvus-tools) to find helpful tools.
