### ISSUE TITLE
[BUG] Cannot find reference 'MetricType' in '__init__.py'

### ISSUE THREAD

**Issue by FangliangBai** [milvus-io/pymilvus#287]
**Describe the bug**
Cannot find reference 'MetricType' in `__init__.py`

**Steps/Code to reproduce behavior**
```sh
$ pip install pymilvus
```
```py
from milvus import MetricType
```

**Expected behavior**
Just fix this bug please.

**Environment details**

- Hardware/Softward conditions (OS, CPU, GPU, Memory)
Ubuntu 16.04
Pycharm 2020.2.3
- Method of installation (Docker, or from source)
pip
- Milvus version (v0.3.1, or v0.4.0)
v0.11.0
- Milvus configuration (Settings you made in `server_config.yaml`)
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/10924189/96710281-c0298980-1393-11eb-9e82-1a469d6c1d84.png)
![image](https://user-images.githubusercontent.com/10924189/96711006-c79d6280-1394-11eb-92c1-296248d7d93b.png)

**Additional context**
N/A

**Comment by BossZou** [comment]
In pymilvus>=0.3.0, pymilvus removed class `MetricType` and `IndexType` and use string to replace. And the usage of metric and index has changed. See [create/drop index](https://github.com/milvus-io/pymilvus#createdrop-indexes-in-a-collection)

**Comment by FangliangBai** [comment]
OK, Thanks.
