### ISSUE TITLE
[BUG]Error occurred. Connection reset by peer

### ISSUE THREAD

**Issue by cs-liwei** [milvus-io/pymilvus#347]
一个http服务里调用了milvus的接口，http服务开启后一段时间（几个小时）后再去访问报下面这个错误。重启http服务又好了。
**Environment details**

-  milvus 0.10.3-cpu

-  pymilvus 0.2.14

```
Addr [127.0.0.1:19530] _cmd
Rpc error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1604451469.114601027","description":"Error received from peer ipv4:127.0.0.1:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}"
>
```

**Comment by cs-liwei** [comment]
@BossZou

**Comment by BossZou** [comment]
@cs-liwei , there is a good way to solve the communication issue. In fact, we use GRPC to transport data from client to server, and this exception is raised by GRPC lib. You are recommend to catch `grpc.RpcError` and try again.
