### ISSUE TITLE
[QUESTION] Best practices for scaling Milvus to ~100 million records?

### ISSUE THREAD

**Issue by shashi-netra** [milvus-io/pymilvus#361]
**What is your question?**
We have a use-case of 100s of millions of 512-dimension vectors that need to be searched for.  Thus far I have added ~15 million records and I see a response time of ~1 sec per query.  

- I am using an `IVF_FLAT` index 
- on an `Intel i7-7700 CPU , GeForce GTX 1080, 64GB RAM`. 
- ` cache.cachesize `to 60GB and 1GB for `insert_buffer_size`.  

I am concerned when it gets to 100M+ the response time might be unacceptably high (5-10 secs). That level of latency is terrible for our UX. Here are some things I am thinking of: 

1. Any recommended upper limit to the collection size (limit to say 5M per collection)
2. Index type: disk-space is not a big concern, should I switch to a different index type from `IVF_FLAT`?
3. 
- Spread the collections across multiple servers and apply a map-reduce style query. In this instance how many collections should I have per server (with the above config)? 
vs.
- a single but much beefier server with more memory and CPU or GPU?
4. Use a more powerful GPU card (say a Titan or RTX?) 

Any Milvus-ers that are able to share their lessons learned in scaling?

**Comment by BossZou** [comment]
@shashi-netra , which version of milvus did you use? And how many times did you teste the response time of per query, the first searching is always slow because milvus could load data from disk then cache it in memory.

**Comment by shashi-netra** [comment]
I used milvus 11 and pymilvus 0.3 and yes I am using multiple calls to check for latency

```
query_embedding = [...]
query_hybrid =  {
     "bool": {
         "must":[
             {
                 "vector": {
                    "embedding": {"topk": 10, "query": query_embedding, "metric_type": "L2", "params": {"nprobe": 10}}
                 }
             }
         ]
     }
}

for i in range(5):
    start_time = time.monotonic()
    results = milvus_client.search(collection_name, query_hybrid, fields=["embedding"])
    end_time = time.monotonic()
    print(timedelta(seconds=end_time - start_time))
```

and I see these results:

```
0:00:02.094116
0:00:01.245215
0:00:01.245218
0:00:01.249103
0:00:01.238358

```

**Comment by BossZou** [comment]
@shashi-netra , I see. The search is slow because you specify fields the search results contains in method `search()` with parameters "fields=['embedding']". If paramater "fields" is not none, milvus could get corresponding field value, and the process is time-consuming. If you don't need get field value in search result, set parameter "fields" None or not pass it, and the search could must faster. Is it necessary to get field values during searching?

**Comment by shashi-netra** [comment]
Thanks! I thought the fields param was specifying which fields to search on. It did improve the performance to: 
```
0:00:00.882363
0:00:00.906604
0:00:00.886910
0:00:00.876127
0:00:00.900354
```
Any chance it can be further improved? Obviously faster == better.

**Comment by BossZou** [comment]
May you show the collection parameters when creating? And you can use index "IVF_SQ8" which is faster than "IVF_FLAT".

**Comment by shashi-netra** [comment]
Thanks I wil try the `IVF_SQ8` type. The collection fields are thus:
 
```
collection_param = {
        "fields": [
            {"name": "length", "type": DataType.INT32},
            {"name": "score", "type": DataType.INT32},
            {"name": "created", "type": DataType.INT32},
            {"name": "embedding", "type": DataType.FLOAT_VECTOR, "params": {"dim": 512}},
        ],
        "segment_row_limit": 9999,
        "auto_id": True
    }
```

**Comment by BossZou** [comment]
You may try to set "segment_row_limit" to be 2,000,000. However, if so, you must create a new collection and then insert data into it, because the collection parameters cannot be modified after created. And you are recommended to set index parameters "nlist" to be 16384.

**Comment by zeynepkoyun** [comment]
@shashi-netra First of all, hi, I am doing the process of adding data to milvus like you, but it is "killed" between 800-1000 records. How did you manage to add the 15000 data you mentioned. Can you share your conf / server_config.yaml file with me?

**Comment by martinenkoEduard** [comment]
> **What is your question?** We have a use-case of 100s of millions of 512-dimension vectors that need to be searched for. Thus far I have added ~15 million records and I see a response time of ~1 sec per query.
> 
> * I am using an `IVF_FLAT` index
> * on an `Intel i7-7700 CPU , GeForce GTX 1080, 64GB RAM`.
> * `cache.cachesize`to 60GB and 1GB for `insert_buffer_size`.
> 
> I am concerned when it gets to 100M+ the response time might be unacceptably high (5-10 secs). That level of latency is terrible for our UX. Here are some things I am thinking of:
> 
> 1. Any recommended upper limit to the collection size (limit to say 5M per collection)
> 2. Index type: disk-space is not a big concern, should I switch to a different index type from `IVF_FLAT`?
> 
> * Spread the collections across multiple servers and apply a map-reduce style query. In this instance how many collections should I have per server (with the above config)?
>   vs.
> * a single but much beefier server with more memory and CPU or GPU?
> 
> 4. Use a more powerful GPU card (say a Titan or RTX?)
> 
> Any Milvus-ers that are able to share their lessons learned in scaling?

Have you managed to resolve this issue?
Btw - don't you use milvus for face recognition?
