### ISSUE TITLE
milvus  自定义向量ID 的作用？

### ISSUE THREAD

**Issue by liutianling** [milvus-io/pymilvus#365]
这是一项非常漂亮有意义的工作，谢谢分享！
有个问题请教下：
milvus.insert() 插入自定义ＩＤ后，之后做向量查询时　milvus.search　, 得到的结果仍然是milvus自动创建的id, 
我想请教的是，这里插入自定义的ID 有什么作用，或者有什么接口能返回自定义ＩＤ而我没有用起来的？
非常感谢！

**Comment by BossZou** [comment]
@liutianling , If you specify id when creating and inserting, milvus could could use them as IDs of entities. If not, it is a bug.
May you present the python sdk and milvus version, and touch your shell code here?

**Comment by liutianling** [comment]
我用的是 python==3.7.9,  milvus_cpu_0.10.0
self.clinet = Milvus(host='192.168.59.69', port='19530')
table_param = {'collection_name': self.index_name, 'dimension':self.vec_dim, 'index_file_size':1024, 'metric_type':MetricType.IP}
self.clinet.create_collection(table_param)
ivf_param = {'nlist': 512}
self.clinet.create_index(self.index_name, index_type=IndexType.IVF_FLAT, params=ivf_param)
status, ids = self.clinet.insert(collection_name=self.index_name,records=vec_list,ids=None)

client.insert 中参数 ids 输入自定义id 后，
返回结果　ids = []
如果输入参数ids=None, 会正常返回　ids  .

**Comment by BossZou** [comment]
@liutianling , may you need to check if `insert()` run rightly:
```
>>> status, ids = client.insert(...)
>>> print(status)
```
if `status.code` is equal to 0, the method is invoked successfully, otherwise, it fail.

**Comment by BossZou** [comment]
Not activate. Close it.
