### ISSUE TITLE
[Document] Wrong description in 'search_in_segment' method

### ISSUE THREAD

**Issue by mzchtx** [milvus-io/pymilvus#371]
**Describe the bug**

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**

- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

[https://pymilvus.readthedocs.io/en/latest/api.html#milvus.Milvus.search](https://pymilvus.readthedocs.io/en/latest/api.html#milvus.Milvus.search)

![image](https://user-images.githubusercontent.com/37564754/100404532-93f0df00-309c-11eb-8981-494a7ed3763f.png)

**Comment by BossZou** [comment]
Thanks for your issue. we'll fix it .

**Comment by BossZou** [comment]
Fixed.
