### ISSUE TITLE
插入向量时报错 AttributeError: 'Milvus' object has no attribute 'bulk_insert'

### ISSUE THREAD

**Issue by Hanlos** [milvus-io/pymilvus#372]
插入embedding向量报错：   AttributeError: 'Milvus' object has no attribute 'bulk_insert'

**Comment by Hanlos** [comment]
之前测试是成功的，不报错，不知道是怎么回事

**Comment by BossZou** [comment]
@Hanlos ,You may try to test the latest example. The latest release version is v0.3.0, so you may to refer to [branch 0.3.0](https://github.com/milvus-io/pymilvus/tree/0.3.0) or [0.3.0 doc](https://pymilvus.readthedocs.io/en/0.3.0/)
