### ISSUE TITLE
[QUESTION] Best way to horizontally scale

### ISSUE THREAD

**Issue by akashmanna** [milvus-io/pymilvus#376]
I currently have milvus running on one server, having ~1Million vectors, and have multiple clients (>100) querying it using pymilvus. The query time increases drastically is there are too many concurrent query requests, so I wanted to scale up horizontally to decrease query times.

Is it possible to maintain replicas and dynamically allocate requests using pymilvus?

What is the best way how I can achieve this?

**Comment by BossZou** [comment]
All of search requests at server endpoints are processed serially. So currently the only way is to load query request balance with multi server nodes. Python client have on effect on it.

**Comment by BossZou** [comment]
Not activate. Close it.
