### ISSUE TITLE
[BUG] Faiss assertion'err == cudaSuccess' failed in void faiss:: gpu::freeMemorySpace(faiss::gpu::MemorySpace, void*) at gpu/utils/MemorySpace.cpp:72; details: Failed to cudaFree pointer 0x7fc514000000 (error 1 invalid argument

### ISSUE THREAD

**Issue by xuyufeng1995** [milvus-io/pymilvus#386]
I tested the code in benchmark0.11.0 three times and he exposed a bug.
1. When setting up the collection, I set the segment_row_limit parameter to 150w and the parameter to 100w, and insert the 118w vector data into milvus. Due to the milvus restriction that each insertion must not exceed 256M, I divided it into multiple insertions, each insertion was 2w, when the insertion was about 110w, the milvus service shut down, the log was Faiss assertion'err == cudaSuccess' failed in void faiss:: gpu::freeMemorySpace(faiss::gpu::MemorySpace, void*) at gpu/utils/MemorySpace.cpp:72; details: Failed to cudaFree pointer 0x7fc514000000 (error 1 invalid argument)
2. The second time I set the segment_row_limit parameter to 150w, the same operation was performed in the previous step, this time no error was reported. So I added the 118w vector again. When it was inserted to about 160w, the milvus service shut down and the log was the same as the previous one.
3. For the third time, I set the segment_row_limit parameter to 400w, and also inserted 226w data into milvus without any problems.
So I think the segment_row_limit directly determines the size of the database, so this problem should be a bug

milvus version:0.11.0
code: https://github.com/milvus-io/bootcamp/tree/0.11.0/benchmark_test/scripts

**Comment by BossZou** [comment]
See [milvus-io/milvus issue 4412](https://github.com/milvus-io/milvus/issues/4412).
