### ISSUE TITLE
[BUG] Pymilvus v0.3.0 "too many values to unpack" if pool parameter is set to QueuePool

### ISSUE THREAD

**Issue by sreisjr** [milvus-io/pymilvus#390]
**Describe the bug**
Experimenting with pool options, after choosing QueuePool, I've got the following error:

```sh
...python3.7/site-packages/milvus/client/pool.py", line 108, in _prepare
    status, version = conn.client().server_version(timeout=30)
ValueError: too many values to unpack (expected 2)
```
**Steps/Code to reproduce behavior**

```python
Milvus(host=self.__addr, port=self.__port, pool="QueuePool")
```

**Expected behavior**
No error in Python code

**Comment by BossZou** [comment]
@sreisjr , thanks for your isssue. This bug will be fixed at next version v0.4.0.
