### ISSUE TITLE
[QUESTION]how does milvus deal with duplicate ids?

### ISSUE THREAD

**Issue by szc11121** [milvus-io/pymilvus#398]
**What is your question?**
if we insert different vectors with same user-defined vector ids, what will happen when we get get_entity_by_id()?
say if we insert [[1,2,3], [2,3,4], [3,4,5]] with ids [0,0,1], when I use get_entity_by_id(collection_name, ids=[0, 1]), milvus return [[1,2,3],[3,4,5]] or [[2,3,4],[3,4,5]] ?

**Comment by BossZou** [comment]
@szc11121 , which version of milvus client and milvus server you used?

**Comment by BossZou** [comment]
@szc11121 , at milvus v0.10.x and v0.11.x, server returns the first found entity. In your case, milvus return [[1,2,3],[3,4,5]].

**Comment by szc11121** [comment]
> @szc11121 , which version of milvus client and milvus server you used?

only know pymilvus==0.2.14, not sure for milvus. It should be v0.10.x but I don't know exactly what x is. And I find there is no api can get the milvus version through pymilvus..

**Comment by szc11121** [comment]
> @szc11121 , at milvus v0.10.x and v0.11.x, server returns the first found entity. In your case, milvus return [[1,2,3],[3,4,5]].

its a little bit weird if I want to get [[1,2,3],[2,3,4]], should I use get_entity_by_id(collection_name, ids=[0, 0])??

**Comment by BossZou** [comment]
> > @szc11121 , at milvus v0.10.x and v0.11.x, server returns the first found entity. In your case, milvus return [[1,2,3],[3,4,5]].
> 
> its a little bit weird if I want to get [[1,2,3],[2,3,4]], should I use get_entity_by_id(collection_name, ids=[0, 0])?? or get_entity_by_id(collection_name, ids=[0, 0]) just return [[1,2,3],[1,2,3]]? so I can never get the vector [2,3,4] by id

If there are some entities which id is the same, milvus only support to get one of them(most possibly the first inserted entity). So you cannot get  [[1,2,3],[2,3,4]]. Therefore, you should make sure ids of entities is unique.
