### ISSUE TITLE
[FEATURE] More meaningful response code, response message, response data

### ISSUE THREAD

**Issue by pvhduc97** [milvus-io/pymilvus#403]
> A clear and concise description of what the problem is.

Currently, when I call delete_entity_by_id(), the pymilvus always return code 0, even when I remove the vector not existed in the collection.

> A clear and concise description of what you want to happen.

I want to know that if the vector is removed successful or not. It is better if pymilvus can return the removed vector.

**Comment by BossZou** [comment]
@pvhduc97 , The method `delete_entity_by_id()` return successfully when vectors was removed or vectors not exist, it only fail when some exception occur during truly deleting vectors .
