### ISSUE TITLE
[BUG] Use gpu with small nq

### ISSUE THREAD

**Issue by nvlong21** [milvus-io/pymilvus#404]
I change config gpu_search_threshold = 1 but time search is very low with small nq.
 - nq=1: time ~15s
 - nq=10: time ~15s
 - nq=1000: time ~11s

**Comment by BossZou** [comment]
@nvlong21 , may you provide more detailed information, such as Milvus version and Pymilvus version, and the way you test search performance including datasize, build index parameters and search parameters?

**Comment by nvlong21** [comment]
Mulvus: 0.11.0
pymilvus: 0.4.0
datasize: 3M 
dim: 512
CPU i3 7700
GPU Nvidia RTX 1660

**Comment by BossZou** [comment]
@nvlong21 ， thanks. May you provide your search parameter DSL here ? And did you specify `fields` during searching?

**Comment by nvlong21** [comment]
Yes, i have specify some field when searching.
DSL: "bool": {
                "must": [
                    {
                        "vector": {
                                "embedding": {"topk":  1, "query": vectors, "metric_type": "L2", "params": {"nprobe": 16}}
                        }
                    }
                ]
            }
fields: "name", "age"

**Comment by BossZou** [comment]
@nvlong21 . I see. If you specify the parameter `fields`, the search performance could be low than that without `fields`.

**Comment by nvlong21** [comment]
@BossZou Oh, thanks you
!

**Comment by BossZou** [comment]
Closing it. Reopen if there is still some problem.
