### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by vipulsharechat** [milvus-io/pymilvus#405]
**What is your question?**
With the newer version 0.10.5, the pymilvus 0.2.15 sdk is required, where is the documentation for that as there are changes in 0.3.0 and 0.2.15 version of pymiluvs ?

**Comment by BossZou** [comment]
@vipulsharechat , see [here](https://pymilvus.readthedocs.io/en/0.3.0/changes.html) about changlog of v0.3.0

**Comment by vipulsharechat** [comment]
That mentions the changelog for 0.3.0, it would be better if you could keep example file for both versions.

**Comment by BossZou** [comment]
@vipulsharechat , currently, if you want to see the previous released version docs and examples, you may need to find that information at corresponding branch. And in the future we'll organize the previous released version docs and manage them in the same website.

**Comment by vipulsharechat** [comment]
Thanks
