### ISSUE TITLE
[QUESTION] Does pymilvus 0.4.0 support searching with term and range?

### ISSUE THREAD

**Issue by junsikh** [milvus-io/pymilvus#410]
Hi, first of all, thanks for developing this wonderful project.
I just noticed that the new version of pymilvus has just been released,
and it seems that it only allows float vectors to be saved in the collections.
Does this change imply that Milvus won't support any other data types like INT and STRING (which has been discussed recently)?

Thank you.

**Comment by BossZou** [comment]
@junsikh , pymilvus 0.4.0 is just a mirror of pymlvus v0.2.15 so it doesn't support searching with term and range.

**Comment by junsikh** [comment]
@BossZou Thank you!
