### ISSUE TITLE
[QUESTION]How to insert auto generated IDS ?

### ISSUE THREAD

**Issue by SilenceBlue** [milvus-io/pymilvus#413]
version: pymilvus==0.4.0
When I provided a user-defined vector ID for insertion, the following problems occurred:

Status(code=12, message='Entities IDs are auto-generated. All vectors of this collection must use auto-generated IDs.')

Therefore, can auto generated IDS be set in version 0.4.0?

**Comment by BossZou** [comment]
@SilenceBlue , if you want to user-defined vector ID for insertion, you need to specify when creating collection: 
```
collection_param = {
   ......
   "auto_id": False     
}

create_collection(collection_name, collection_param)
```
The value of "auto_id" means:
   False - User specify vector ID during inserting
   True  - Vector ID is generated automatically

----------------------------------------------------------------------------------------------------------------------------
