### ISSUE TITLE
WORKER TIMEOUT with uvicorn 

### ISSUE THREAD

**Issue by LightToYang** [milvus-io/pymilvus#418]
WORKER TIMEOUT with uvicorn 
```
_HOST = 'milvusserver'
_PORT = '19530'
milvus_client = Milvus(_HOST, _PORT)       # stuck here
```

**Comment by BossZou** [comment]
@LightToYang , please provide the Pymilvus version and Milvus version.

**Comment by LightToYang** [comment]
@BossZou 
Inlcluding the following code by mistakes like #194 
```
from grpc.experimental.gevent 
import init_gevent from gevent 
import monkey monkey.patch_all() init_gevent()
```
uvicorn works fine with milvus-0.10.5 and pymilvus-0.4.0

**Comment by BossZou** [comment]
@LightToYang , I see. I found a official solution in gRPC issue channel [gevent compatibility](https://github.com/grpc/grpc/issues/4629#issuecomment-376962677), where may be helpful.
