### ISSUE TITLE
milvus.search params 

### ISSUE THREAD

**Issue by cceyda** [milvus-io/pymilvus#428]
I'm just starting out with milvus and I have some questions about `milvus.search` that I think are not clearly covered in the [docs](https://www.milvus.io/docs/v0.10.6/search_vector_python.md)

what are the valid `params` for `milvus.search` besides `nprobe`, is there a reference for those that I can look at? Is it the same as faiss [docs](https://github.com/facebookresearch/faiss/wiki/Faster-search)?
Does milvus.search always use cache? Is there an option to turn cache off for only certain queries like `cache=False`?

Thank you~

**Comment by BossZou** [comment]
@cceyda , you can refer to [Vector Index](https://milvus.io/cn/docs/v0.10.6/index.md) to get detailed index information.

**Comment by jmugan** [comment]
@cceyda Did you find a solution to turning off the cache? We need to show that adding new vectors improves the results but I think the cache is preventing that.
