### ISSUE TITLE
[QUESTION] The total time for async processing is the same as sync processing 

### ISSUE THREAD

**Issue by leviethung2103** [milvus-io/pymilvus#429]
**What is your question?**
HI author, 
Thank you for creating such a useful examples of pymilvus. I've tried the `example_async.py` file and I realized that the total processing time is the same as sync processing. 

I made a change to every function that used async=True to the normal function. 

I want to ask you whether `async` processing will be faster than `sync` processing method. 

Thank you in advance.

**Comment by BossZou** [comment]
@leviethung2103 , if you make a single `async` processing, the time cost is nearly the same as a single `sync` processing. but you can make multiple `async` processing to send concurrent requests.

**Comment by leviethung2103** [comment]
Thank you @BossZou, I got your points here. Basically, at a certain point of time, we can make multiple requests. This is a style of non-blocking processing.
