### ISSUE TITLE
Error when insert data: "grpc_message":"keepalive watchdog timeout","grpc_status":14

### ISSUE THREAD

**Issue by xiaotown123** [milvus-io/pymilvus#449]
pymilvus version: 0.3.0
milvus server version: 0.11.0

error meassage is:

Addr [10.32.76.108:19530] insert
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1615451178.228000000","description":"Error received from peer ipv4:10.32.76.108:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
>

**Comment by BossZou** [comment]
It seem like your server is stuck and no respond for client ping request. You need to check if your server run well.

**Comment by xiaotown123** [comment]
> It seem like your server is stuck and no respond for client ping request. You need to check if your server run well.

I have solved the problem with modifing this code in grpc_handler.py. I suggest client can open a api to set this param.
thanks for your reply

![image](https://user-images.githubusercontent.com/6803181/111238386-f660f180-8631-11eb-94e8-1d0d5b45bdaa.png)
