### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by BossZou** [milvus-io/pymilvus#458]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by XuanYang-cn** [comment]
I'll test if pymilvus for Python3.9 is a problem now

**Comment by XuanYang-cn** [comment]
python3.9 for Milvus2.0 works fine。

**Comment by XuanYang-cn** [comment]
Already tested on Python3.0
