### ISSUE TITLE
partially initialized module 'milvus' has no attribute 'Milvus' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Peter-Chou** [milvus-io/pymilvus#463]
**Describe the bug**
after installing the pymilvus, i got an error when runing example.py
``` sh
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from milvus import Milvus, IndexType, MetricType, Status
  File "/home/peter/projects/insurance_qa/milvus.py", line 6, in <module>
    milvus_db = milvus.Milvus(host='localhost', port='19530')
AttributeError: partially initialized module 'milvus' has no attribute 'Milvus' (most likely due to a circular import)
```

**Steps/Code to reproduce behavior**

``` sh
# python version: 3.8.8
pip install pymilvus==1.0.1
wget https://raw.githubusercontent.com/milvus-io/pymilvus/v1.0.1/examples/example.py
python example.py
```

**Environment details**

- Hardware/Softward conditions: CPU
- Method of installationL Docker
- Milvus version: 1.0.0
- Milvus configuration: defaults in `server_config.yaml`

**Screenshots**
![image](https://user-images.githubusercontent.com/28672146/111949148-279e5d80-8b1b-11eb-9b72-2dc23cdcf5c1.png)

**Additional context**

**Comment by BossZou** [comment]
@Peter-Chou  just change `milvus_db = milvus.Milvus(host='localhost', port='19530')` to `milvus_db = Milvus(host='localhost', port='19530')` and try again.

**Comment by Peter-Chou** [comment]
@BossZou, thank you for your suggestion.  I finally figured out that I accidentally renamed a test file to milvus.py, which cause the circular import problem. After removing milvus.py, everything works as expected.
