### ISSUE TITLE
What does insert_hybrid in the source code mean?

### ISSUE THREAD

**Issue by Wenorm** [milvus-io/pymilvus#466]
Why does the insert method of v1.0.0 only insert vectors instead of entities containing multiple fields? Is insert_hybrid a way to insert entities with multiple fields? But it is still in an unavailable state.
![image](https://user-images.githubusercontent.com/75149614/112272219-ddea7a00-8cb6-11eb-8161-cd6e1f80c11f.png)

**Comment by BossZou** [comment]
@Wenorm , Multiple fields is not supported in python sdk v1.0.0. And the hybrid-related method is not exposed to user, which are just experimental and will be removed.

**Comment by Wenorm** [comment]
> Why does the insert method of v1.0.0 only insert vectors instead of entities containing multiple fields? Is insert_hybrid a way to insert entities with multiple fields? But it is still in an unavailable state.
> ![image](https://user-images.githubusercontent.com/75149614/112272219-ddea7a00-8cb6-11eb-8161-cd6e1f80c11f.png)

**Comment by Wenorm** [comment]
@BossZou Are there plans to support multiple fields in one entity in the future? The previous version had multiple fields. If the latest version does not support it, it will be difficult to iterate on the previous code.

**Comment by BossZou** [comment]
@Wenorm ,We plan to release a real-distributed version in the future which will support multiple fields, you can find more details [here](https://github.com/milvus-io/milvus/discussions/4793).
