### ISSUE TITLE
topk对同一人不同人员id时不适用

### ISSUE THREAD

**Issue by L-lei** [milvus-io/pymilvus#475]
topk对同一人不同人员id时不适用,通过计算距离值大于或者小于返回数据
场景如人脸识别中,小明相对小明妻子是丈夫,小明相对小明父亲是儿子,小明相对小明女儿是父亲...;这样就有n个小明的人员id,但他们都是小明,查询时需要返回这些所有的id;

但是当前返回数据是根据topk返回指定个数,当topk小于所有图片的个数时就会出现,查询结果中只有部分人员id;
如30个人员id都是小明且库中每个人员id只有一张图片,topk设置为5时,只返回5个人员id,很可能出现我想得到的数据不在返回结果中

**Comment by XuanYang-cn** [comment]
@L-lei  With vector similarity search, you are able to get pictures that **are similar to** Xiao Ming's picture, but you're not able to get pictures that **are related to** Xiao Ming, Pictures don't have relations among them. 

You will get ALL XiaoMing's relations **If and only if they ALL look alike, which is usually impossible.**

Typically, XiaoMing's relations will have their own vectors and ids, they can't be sharing the same id, cause they are not the same person. 

Briefly, in similarity search, we can't search relations, we search similarity.

**Comment by L-lei** [comment]
Yes, Milvus calculates the similarity between features. 
For example, Xiaoming is the boss of company A/B/C. 
he is the boss of three different companies and has different user_id But they are all the same person;
In Milvus, there are 100 face features of Xiaoming in company A, 10 face features of Xiaoming in company B, and 1 face feature of Xiaoming in company C. 
if top_k=5,  then only sum([(1 / (100 + 10 + 1)) for i in range (5)])=0.045 returns Xiaoming face feature ID of company C
Actually need to return A/B/C company Xiaoming's face feature ID

**Comment by L-lei** [comment]
Thank you for your help. 
Yes, Milvus calculates the similarity between features. 
For example, Xiaoming is the boss of company A/B/C, he is the boss of three different companies and has different user_id But they are all the same person;
In Milvus, there are 100 face features of Xiaoming in company A, 10 face features of Xiaoming in company B, and 1 face feature of Xiaoming in company C. 
if top_k=5,  then only sum([(1 / (100 + 10 + 1)) for i in range (5)])=0.045 returns Xiaoming face feature ID of company C
Actually need to return A/B/C company Xiaoming's face feature ID

**Comment by L-lei** [comment]
Thank you for your help. 
Yes, Milvus calculates the similarity between features. 
For example, Xiaoming is the boss of company A/B/C, he is the boss of three different companies and has different user_id But they are all the same person;
In Milvus, there are 100 face features of Xiaoming in company A, 10 face features of Xiaoming in company B, and 1 face feature of Xiaoming in company C. 
If top_k=5,  then only sum([(1 / (100 + 10 + 1 - n)) for n in range (1,6)])=0.0463 returns Xiaoming face feature ID of company C
Actually need to return A/B/C company Xiaoming's face feature ID

**Comment by XuanYang-cn** [comment]
@L-lei
In Milvus-1.0, Your case can be solved by creating some `partition`s naming company A, B, C in one collection and insert vectors accordingly.  You can set which partition to search in, and gather the results.

**Comment by L-lei** [comment]
[@XuanYang-cn](https://github.com/XuanYang-cn) I used other methods to solve this problem. This is only a problem I found when I used the API. It doesn't affect the overall use of Milvus

**Comment by L-lei** [comment]
[@XuanYang-cn](https://github.com/XuanYang-cn) I used other methods to solve this problem. This is only a problem I found when I used the API. It doesn't affect the overall use of Milvus
