### ISSUE TITLE
New api in pymilvus is needed

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#476]
- [x] edit `get_entity_by_id()`, add a new parameter `partition_tag`
- [x] edit `delete_entity_by_id()` add a new parameter `partition_tag`
- [x] add a new api `release_collection(collection_name: str, partition_tags: list)`

**Comment by XuanYang-cn** [comment]
- [ ] First change docs

**Comment by XuanYang-cn** [comment]
Done

**Comment by keotic** [comment]
@XuanYang-cn 
With the implementation of these functions, can we insert different entities with the same id to different partitions on the same collection?

**Comment by XuanYang-cn** [comment]
@keotic Yes, we are able to do it, even before this enhancement.
