### ISSUE TITLE
Does milvus stopped supporting query DSL and filtering?[QUESTION]

### ISSUE THREAD

**Issue by keotic** [milvus-io/pymilvus#480]
**What is your question?**
Updating to Milvus 1.0 and Pymilvus 1.0.1 I see that the search interface lacks the dsl parameter.
Is this feature not supported anymore? How can we filter searches?

**Comment by XuanYang-cn** [comment]
milvus 1.x don't support dsl, but upcoming milvus 2.0 supports dsl, looking forward to it ;)

**Comment by keotic** [comment]
@XuanYang-cn 
Cool, is there an ETA on milvus 2.0 release?

**Comment by XuanYang-cn** [comment]
Currently, it's unavailable. You can get a notify with [this link](https://zilliz.com/cloud).
Milvus 2.0 is based on a brand new cloud-native structure and will be open source in notime.
