### ISSUE TITLE
Why example.py use `or` to test query result distance and ids

### ISSUE THREAD

**Issue by qweeze** [milvus-io/pymilvus#481]
This [line](https://github.com/milvus-io/pymilvus/blob/master/examples/example.py#L111) in example.py
```python
if results[0][0].distance == 0.0 or results[0][0].id == ids[0]:
    print('Query result is correct')
```
shouldn't it be
```python
if results[0][0].distance == 0.0 and results[0][0].id == ids[0]:
    print('Query result is correct')
```
?

**Comment by XuanYang-cn** [comment]
@qweeze  With `IVF_FLAT` index, if some vectors are the same but ids are different, the distances will be zero but ids may not be the same. So we use `or`.

With other indexes like `SQ8H`, the distance won't be zero but the ids are the same, so we use `or`

**Comment by qweeze** [comment]
I see, thanks!
