### ISSUE TITLE
[BUG] Rpc error, details = "keepalive watchdog timeout" in search

### ISSUE THREAD

**Issue by ArtemSmeta** [milvus-io/pymilvus#489]
**Describe the bug**
When using pymilvus == 1.0.1 with flask, gunicorn[gthread] applications. When executing exactly the second request to search for a vector, an error appears. "the functionality does not work for a minute, after which everything works stably.

**Steps/Code to reproduce behavior**
```
def get_most_similar(collection_name: str,
                   partition_tags: str,
                   vector: List[float],
                   top_k: int = 10,
                   nprobe: int = 128) -> List[Tuple[int, TopKQueryResult]]:
  search_param = {'nprobe': nprobe}
  vector = vector / np.linalg.norm(vector)
  vector = vector.tolist()


  status, results = client.search(collection_name=collection_name,
                                      query_records=[vector],
                                      top_k=top_k,
                                      partition_tags=[partition_tags],
                                      params=search_param)
```

**Expected behavior**

**Environment details**

- Hardware/Softward conditions (CPU)
- Method of installation (Docker - milvusdb/milvus:1.0.0-cpu-d030521-1ea92e)
- Milvus version (v1.0.1)

**Screenshots**
![Screenshot from 2021-04-20 15-21-39](https://user-images.githubusercontent.com/43440709/115395084-23ce2b80-a1ec-11eb-9098-0e07065229fb.png)

**Comment by XuanYang-cn** [comment]
@ArtemSmeta  We need more information to reproduce this, please fire a more detailed issue [here](https://github.com/milvus-io/milvus/issues/new?assignees=&labels=&template=bug_report.md&title=). It's more likely something wrong in milvus.
