### ISSUE TITLE
[BUG] VersionError: Version of python SDK(1.1.0) not match that of server1.0.0, excepted is ('1.1.x',)

### ISSUE THREAD

**Issue by shashi-netra** [milvus-io/pymilvus#506]
**Describe the bug**
I am trying to connect to milvus server using the latest pymilvus client and keep getting the above error. I can connect fine from other machines and seems limited to this instance.

`VersionError: Version of python SDK(1.1.0) not match that of server1.0.0, excepted is ('1.1.x',)`

```
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import milvus
>>> milvus.__version__
'1.1.0'
```

This is a weird error message, can anyone help clarify?

**Environment details**
Ubuntu 20.0, Python 3.6.9

Do I need to upgrade the server to 1.1.x? or downgrade pymilvus client to 1.0.0 (I tried this with no luck)

**Comment by shashi-netra** [comment]
OK i figured out a workaround for anyone else running into this issue: `pip3 install pymilvus==1.0.1`. It's the `V1.0.1 `that did the trick (not v1.0.0). Project developers, please take note of this bug.

**Comment by XuanYang-cn** [comment]
@shashi-netra Thanks for noticing.

The latest pymilvus(v1.1.0) is not supposed to compatible with server version 1.0.x. So the highest pymilvus version for milvus1.0.x is pymilvus(v1.0.1). You are doing the right thing.
