### ISSUE TITLE
[BUG] Docker Segmentation fault - on GRPC connection

### ISSUE THREAD

**Issue by keotic** [milvus-io/pymilvus#507]
**Describe the bug**
Inside a docker image, running with DockerCompose, when trying to connect to Milvus via GRPC (default) 
Docker failed with Segmentation fault. When connecting with HTTP + HTTP port it works OK.

**Steps/Code to reproduce behavior**
Milvus DB Docker image:  milvusdb/milvus:1.1.0-cpu-d050721-5e559c

Create another image with pymilvus client and call:

milvus = Milvus(host='dokcer_compose_service_name', port=19530, handler='GRPC')  - Segmentation Fault
and get a segmentation fault.

milvus = Milvus(host='dokcer_compose_service_name', port=19121, handler='HTTP')  - is OK

Run it with docker compose.

**Expected behavior**
No Segmentation Fault or a detailed error

**Environment details**
Milvus DB Docker image:  milvusdb/milvus:1.1.0-cpu-d050721-5e559c

Client image : 
based on python:3.7-slim-buster (FROM python:3.7-slim-buster)
pymilvus 1.1.0

- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
- Milvus configuration : default version 0.6

**Comment by XuanYang-cn** [comment]
@yhmo

**Comment by keotic** [comment]
@yhmo have you managed to reproduce the Segmentation fault?

**Comment by yhmo** [comment]
@keotic 

The grpc tool version is too old in the client container.
Create a file named "requirement.txt" in your client container, paste these in to the file:
```
grpcio==1.22.0
grpcio-tools==1.22.0
```
Then install it:
`pip install -r requirement.txt`

After install, it will be ok.

**Comment by keotic** [comment]
@yhmo Thanks, problem solved

**Comment by XuanYang-cn** [comment]
closing this issue for problem solved.

**Comment by anitas49** [comment]
Hi.
 I ran across this issue as well and my grpcio/grpcio-tools version is 1.32.0 and  1.37.1. Can i only use the version you mention?
 
 Env detail:
 - pymilvus 1.1.0
 - Docker image: milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
 - python 3.8

**Comment by rky0930** [comment]
I tested it and `grpcio==1.37.0` and `grpcio-tools==1.37.0`  also seems to work. Strange thing is 1.38.0 has Segfault.

**Comment by yhmo** [comment]
The milvus project use a grpc project diverse from the official grpc master branch, in Dec 2019:
https://github.com/milvus-io/grpc-milvus

The custom project removed some third-parties and fix one issue(I am not sure). It could not match with too old/new proto version I guess.
