### ISSUE TITLE
[BUG] Fatal Python error: Segmentation fault while connecting to Milvus server from VM client with default GRPC

### ISSUE THREAD

**Issue by anitas49** [milvus-io/pymilvus#517]
**Describe the bug**
In our CICD vm, I installed pymilus, connect to Milvus server with default GRPC. The test fail with `Fatal Python error: Segmentation fault` error

**Steps/Code to reproduce behavior**

1. Create a Docker image wrapped with Milvus based image use the following and run the following built image
```
FROM milvusdb/milvus:1.1.0-cpu-d050721-5e559c

RUN mkdir -p /var/lib/milvus/conf
COPY ./operations/docker/milvus/server_config.yaml /var/lib/milvus/conf
WORKDIR /var/lib/milvus/
```
2. Have CICD VM in another image and call by using:

`milvus = Milvus(uri='tcp://{host_address}:{port}')` Then the error popped up

**Expected behavior**
Should connect to milvus server without this error

**Environment details**
python 3.8
pymilvus==1.1.0
Milvs configuration change `cache.cache_size: 512MB` , `insert_buffer_size:256MB`

I saw a [similar issue](https://github.com/milvus-io/pymilvus/issues/507) but I checked my client's grpcio, grpcio-tools version is >= 1.22.0 so its newer than `1.22.0` and there are some minor setting which are different from that ticket. I use uri argument to connect to my server rather than host and post tho.
 
```
grpcio=1.32.0
grpcio-tools =1.37.1
```

**Comment by tsvs** [comment]
Hi there, it seems that pymilvus is working only with `grpcio==1.22.0` and `grpcio-tools==1.22.0`. I face the same segmentation fault on any version of grpcio above 1.22.0

**Comment by rky0930** [comment]
I tested it and `grpcio==1.37.0` and `grpcio-tools==1.37.0`  also seems to work.

**Comment by wallies** [comment]
Since there is a http and grpc APIs couldnt you do an extras requires so you could only install whats needed for http and have the extras for grpc?
