### ISSUE TITLE
Why generate protobuf python_out in `gen/` and then copy the files into `pymilvus/grpc_gen`

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#561]
#### Furthermore, every time we copy the generated files into `pymilvus/grpc_gen`, we make these changes, why?

```python
# before copy milvus_pb2.py from `gen/`
import common_pb2 as common__pb2
```
will be manuly changed into 
```python
# after copy milvus_pb2.py into `pymilvus/grpc_gen`
from . import common_pb2 as common__pb2
```

Can't we generate python codes in relative import directly?

#### Isn't there a solution to avoid `manul` operations in this process.

**Comment by XuanYang-cn** [comment]
@czs007 Do we have any progress yet?

**Comment by czs007** [comment]
not yet. Just wait.
