### ISSUE TITLE
import error: can not import DataType

### ISSUE THREAD

**Issue by pokerc** [milvus-io/pymilvus#575]
follow the demo doc, but import failed.
pymilvus 1.1.2
`from milvus import DataType`
error msg:
`ImportError: cannot import name 'DataType'`

any solutions?

**Comment by miangangzhen** [comment]
I meet same problem

**Comment by XuanYang-cn** [comment]
The `master` brach is holding code of PyMilvus 2.x. 

you can refer to examples in branch  `1.x` , which represent the "master" of the PyMilvus 1.x

@miangangzhen @pokerc 

2.x isn't compatible with 1.x, that's why 2.x's examples don't work for 1.x
