### ISSUE TITLE
AttributeError: 'Connections' object has no attribute 'connect'

### ISSUE THREAD

**Issue by zzy0222** [milvus-io/pymilvus#586]
I downloaded example code from https://github.com/milvus-io/pymilvus-orm/blob/main/examples/hello_milvus.py.
But it can't run. 
"connections.connect()" this line return errors.
But I checked API references from here: https://pymilvus-orm.readthedocs.io/en/latest/tutorial.html
Official tutorial gives an example like:
host = '127.0.0.1'
port = '19530'
connections.connect("default", host=host, port=port)

And I checked Class Connection, and found attribute 'connect' doesn't exist.
![image](https://user-images.githubusercontent.com/33983604/123734880-bf58d800-d8d0-11eb-8430-7f02ac711be2.png)
So, could someone help me! Thx very much~~

**Comment by leonardokidd** [comment]
I resolved this issue by using create_connection() instead of just connect function. Potentially, you may also need to make some code change in Milvus.

**Comment by XuanYang-cn** [comment]
@zzy0222, Of course we have `connect()` in PyMilvus-ORM, make sure your `PyMilvus-ORM` version equals to `2.0.0rc1`, it's a pre-release version, you'll need to give the version manually like `pip3 install pymilvus-orm==2.0.0rc1`

source:
 https://github.com/milvus-io/pymilvus-orm/blob/f95b125b82907ea89b51c8689307a71d47f2e9b1/pymilvus_orm/connections.py#L119

You can check [PyMilvus-ORM repo](https://github.com/milvus-io/pymilvus-orm)

**Comment by XuanYang-cn** [comment]
> I resolved this issue by using create_connection() instead of just connect(). I believe this is your pymilvus_orm's issue. You may want to check if you installed pymilvus_orm==2.0.0rc1.

@leonardokidd Thanks for helping us, actually `create_connection()` is replaced by `connect()` in the latest PyMilvus-ORM

**Comment by zzy0222** [comment]
> I resolved this issue by using create_connection() instead of just connect(). I believe this is your pymilvus_orm's issue. You may want to check if you installed pymilvus_orm==2.0.0rc1.

Thanks for helping me~

**Comment by zzy0222** [comment]
> > I resolved this issue by using create_connection() instead of just connect(). I believe this is your pymilvus_orm's issue. You may want to check if you installed pymilvus_orm==2.0.0rc1.
> 
> @leonardokidd Thanks for helping us, actually `create_connection()` is replaced by `connect()` in the latest PyMilvus-ORM

Thanks very much, I reinstalled pymilvus_orm==2.00rc1, and problem is solved.
And I close this issue.
