### ISSUE TITLE
pymilvus_orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=The types of schema and data do not match.)>

### ISSUE THREAD

**Issue by zzy0222** [milvus-io/pymilvus#588]
I'm a little confused about whether pymilvus==2.0.0rc1 supports STRING field. 
I want to add an string type of field in schema. From official guide, I know that pymilvus now still doesn't support STRING from here: https://milvus.io/docs/v2.0.0/comparison.md
![image](https://user-images.githubusercontent.com/33983604/123932458-0e336a00-d9c4-11eb-809e-baab55865d57.png)
But I find DataType.STRING when I try to change the 'dtype' of field.
![image](https://user-images.githubusercontent.com/33983604/123932818-64a0a880-d9c4-11eb-92b8-9677010e1b41.png)
I revise the variable type, and this error occurs. 
So, **my first question** is does pymilvus==2.0.0rc1 support STRING field?

If not, here is my demand.
I try to put STRING information to a collection. If 'dtype' only can be number, I want to encode names of my data as a long integer. Use the code like that.

```python
def encode_string_to_int(mystring):
    mybytes = mystring.encode('utf-8')
    myint = int.from_bytes(mybytes, 'little')
    return myint


def decode_int_to_string(myint):
    recoveredbytes = myint.to_bytes((myint.bit_length() + 7)
                                    // 8, 'little')
    recoveredstring = recoveredbytes.decode('utf-8')
    return recoveredstring
```
For example, I want to encode a name 'test_video'. But it's too long after encoding, and I got the exception below.
```
Addr [localhost:19530] bulk_insert
Excepted error: Value out of range: 526053036194403978536308
```
So, **my second question** is how can I encode any long string into a INT64 variable?
Looking forward to your reply. Thanks!

**Comment by XuanYang-cn** [comment]
1. Don't support string field right now.
2. `mmh3` hash will do it. Please refer to the [repo](https://github.com/hajimes/mmh3)

Shortly
```python
>>> import mmh3
>>> mmh3.hash("foo", signed=False) # returns a 32-bit unsigned int
4138058784
```

**Comment by zzy0222** [comment]
> @zzy0222
> 
> 1. Don't support string field right now, but will support it at v2.0.0 Release
> 2. `mmh3` hash will do it. Please refer to the [repo](https://github.com/hajimes/mmh3)
> 
> Shortly
> 
> ```python
> >>> import mmh3
> >>> mmh3.hash("foo", signed=False) # returns a 32-bit unsigned int
> 4138058784
> ```

Thanks!
I find mmh3 seems only can encode a string, but can't decode an integer to a string.

**Comment by zzy0222** [comment]
Thanks for your reply. It seems no effective way of decoding an integer to a string. And I closed the issue~
