### ISSUE TITLE
[QUESTION] Why We seperate pymilvus and pymilvus-orm/

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/pymilvus#597]
**What is your question?**

Hi All, I'm thinking of combining pymilvus and the pymilvus-orm repo. Is there any blocking issues for us to do so?
Separate two apis doesn't make sense to me especially when pymilvus and orm are both supported in the long run.
Any comments, suggestions?

**Comment by xiaofan-luan** [comment]
@XuanYang-cn @yanliang567 @czs007 @scsven @xiaocai2333  want your opinions

**Comment by xiaofan-luan** [comment]
I think combining repos will help us on cleanup codes and make release easier.

**Comment by yanliang567** [comment]
I agree and suggest
1. combine into 1 repo
2. combine into 1 package for client
3. combine into 1 testing ci pipeline for regression

**Comment by xiaofan-luan** [comment]
> I agree and suggest
> 
> 1. combine into 1 repo
> 2. combine into 1 package for client
> 3. combine into 1 testing ci pipeline for regression

that's exactly what i want to do, didn't fine a exact reason to do so.

**Comment by scsven** [comment]
When I fix a bug in pymilvus, it publishes a new version, so that I should also upgrade the dependent pymilvus version in pymilvus-orm, and then I can fix the issue in

**Comment by xiaofan-luan** [comment]
@XuanYang-cn How about helping us on combing milvus and pymilvus repo? also the documents need to be updated

**Comment by XuanYang-cn** [comment]
@xiaofan-luan Alright, I'll draft a MEP on how to combine these 2 repos.
