### ISSUE TITLE
[BUG] "DefaultConfig" could not be imported

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#634]
**Describe the bug**
"DefaultConfig" could not be imported when importing through "from pymilvus import DefaultConfig"

E   ImportError: cannot import name 'DefaultConfig' from 'pymilvus' (/Users/binbin/Library/Python/3.8/lib/python/site-packages/pymilvus/__init__.py)

**Steps/Code to reproduce behavior**
from pymilvus import DefaultConfig

**Expected behavior**
imported successfully without errors

**Environment details**

- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
pymilvus: Version: 2.0.0rc5.dev12

- Milvus configuration (Settings you made in `server_config.yaml`)
standalone

**Screenshots**

**Additional context**

**Comment by XuanYang-cn** [comment]
Fixed on `pymilvus-2.0.0rc5.dev13`

**Comment by binbinlv** [comment]
Fixed.
pymilvus-2.0.0rc5.dev13
