### ISSUE TITLE
[BUG] "ExceptionsMessage" could not be imported

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#636]
**Describe the bug**
"ExceptionsMessage" could not be imported through "from pymilvus import ExceptionsMessage"

**Steps/Code to reproduce behavior**
from pymilvus import ExceptionsMessage

**Expected behavior**
imported successfully without errors

**Environment details**

- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
pymilvus-2.0.0rc5.dev13
- Milvus configuration (Settings you made in `server_config.yaml`)
standalone

**Screenshots**

**Additional context**

**Comment by XuanYang-cn** [comment]
fixed on `pymilvus-2.0.0rc5.dev14`

**Comment by binbinlv** [comment]
Fixed.

version:
pymilvus-2.0.0rc5.dev14
