### ISSUE TITLE
[FEATURE] Update grpc-generated files using the grpc version specific in setup.py

### ISSUE THREAD

**Issue by DragonDriver** [milvus-io/pymilvus#641]
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]
should resolve #640 

**Describe the solution you'd like**
Update grpc-generated files using the grpc version specific in setup.py. Recompile `schema.proto`, `common.proto` and `milvus.proto`. In the meanwhile, we should limit the version of `grpcio` defined in setup.py to a specifc version instead of a range version.

**Describe alternatives you've considered**

**Additional context**

**Comment by XuanYang-cn** [comment]
Recommend: `1.37.1`

**Comment by DragonDriver** [comment]
We should also mention this in our contributing guide. All developers of this repo should use the specifc grpc version to generate the related files.

**Comment by DragonDriver** [comment]
But how do we know which version of grpc was used by developers?
