### ISSUE TITLE
[QUESTION] Differences between two distance metric in example.py

### ISSUE THREAD

**Issue by XiaoConstantine** [milvus-io/pymilvus#649]
**What is your question?**
What's the differences between this two definition of distance metric for collection creation?
https://github.com/milvus-io/pymilvus/blob/master/examples/old_style_example.py#L43

https://github.com/milvus-io/pymilvus/blob/master/examples/old_style_example.py#L45

**Comment by XuanYang-cn** [comment]
Good question! Actually, L43 and L45 are both invalid params (but not harmful).

Distance metrics are params for building indexes.

Unlike `Milvus 1.x`, `Milvus 2.x` creates an index only if you called `create_index()` with the index params, L43 AND L45 won't be used in `Milvus 2.x`.

This's a bug in this example, we will fix it soon.

**Comment by XiaoConstantine** [comment]
I see. I m trying to migrate from 0.10.5 to 2.x. Is there a good example demonstrate properly migrate from old API?

**Comment by XuanYang-cn** [comment]
> I see. I m trying to migrate from 0.10.5 to 2.x. Is there a good example demonstrate properly migrate from old API?

We don't have examples for migration, you can check https://milvus.io/api-reference/pymilvus-orm/v2.0.0rc4/tutorial.html for new API usages.

Or, if in need, you may file an issue of demanding this migration demo on https://github.com/milvus-io/milvus/issues/new?assignees=&labels=kind%2Fenhancement&template=enhancement.md&title=

**Comment by XiaoConstantine** [comment]
I see, thanks, closing this.
