### ISSUE TITLE
Timeout not modifiable

### ISSUE THREAD

**Issue by natemccoy** [milvus-io/pymilvus#651]
https://github.com/milvus-io/pymilvus/blob/229f5aa48eb4ef6020508714f562b855b291a1f6/pymilvus/client/stub.py#L179

Milvus client does not allow for timeout changes even thought the kwargs could support it on instantiation of the `Milvus` class.

Issue occurs as no args are passed to `_wait_for_healthy` function

**Comment by XuanYang-cn** [comment]
Thanks for pointing it out.

I think it's a simple change

```python
def _wait_for_healthy(self, timeout=30, retry=10):
    _timeout_on_every_retry = self._kw.get("timeout", None)
    _timeout = _timeout_on_every_retry if _timeout_on_every_retry else timeout
    ...
        if (time.time() - start_time > _timeout):
    ...
            status = handler.fake_register_link(_timeout)
```

Would you like to fix the bug?

BTW, If this's no feedbacks for several days, I'll fix it myself.
