### ISSUE TITLE
Need an example of getting an existing collection in example, tutorial, etc.

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#670]
from https://github.com/milvus-io/pymilvus-orm/issues/280

people are asking in slack and wechat about how to get an existing collection by pymilvus_orm?
so we need an example in examples, turoial and api doc.
```
c = Collection(existing_collection_name)
```

**Comment by shiyu22** [comment]
How about adding `test_exist_collection` function to [collection.py](https://github.com/milvus-io/pymilvus/blob/master/examples/collection.py)
