### ISSUE TITLE
Failed to load data to Milvus: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by LeeREVO** [milvus-io/pymilvus#679]
When insert data to Milvus, I got a exception "Failed to load data to Milvus: list indices must be integers or slices, not str", but I don't have any str in entities, someone know what was going wrong?

**Comment by XuanYang-cn** [comment]
Please provide the python codes and version of pymilvus

**Comment by LeeREVO** [comment]
My collection info is:
`"fields": [
        {
            "field_id": 100,
            "name": "id",
            "description": "",
            "type": 5,
            "params": {},
            "is_primary": true,
            "auto_id": true
        },
        {
            "field_id": 101,
            "name": "embedding",
            "description": "",
            "type": 101,
            "params": {
                "dim": 2048
            },
            "is_primary": false,
            "auto_id": false
        },
        {
            "field_id": 102,
            "name": "car_id",
            "description": "",
            "type": 5,
            "params": {},
            "is_primary": false,
            "auto_id": false
        },
        {
            "field_id": 103,
            "name": "camera_id",
            "description": "",
            "type": 5,
            "params": {},
            "is_primary": false,
            "auto_id": false
        }
    ]
`
and the codes for loading data could be simplified like this:
`
The_Traffic = [
        {
            "camera_id": 1,
            "car_id": 2001,
            "embedding": [random.random() for _ in range(2048)]
        },
        {
            "camera_id": 2,
            "car_id": 2002,
            "embedding": [random.random() for _ in range(2048)]
        },
        {
            "camera_id": 3,
            "car_id": 2003,
            "embedding": [random.random() for _ in range(2048)]
        }
    ]

    car_id = [k.get("car_id") for k in The_Traffic]
    embeddings = [k.get("embedding") for k in The_Traffic]
    camera_id = [k.get("camera_id") for k in The_Traffic]
    data = [embeddings, car_id, camera_id]
    milvus = Milvus(_HOST, _PORT)
    ids = milvus.insert("collection_name", data)
`

I'm using pymilvus==2.0.0rc4

**Comment by LeeREVO** [comment]
Kindly let me know if there are defects in my code，really appreciate it~~

**Comment by XuanYang-cn** [comment]
Sorry for the late, We recommend use ORM-style API. Your codes are old APIs, they don't have docs, thus harder to use and find why.

BTW, your code isn't working because `insert()` in not in use now, you'll have to use `bulk_insert` if you insist.

Refer to the newest ORM [example](https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py)

**Comment by LeeREVO** [comment]
Great~~！Thank you for the detailed explanation
