### ISSUE TITLE
[BUG] Link of docs in Readme is pointed into readthedocs

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#684]
Should be https://milvus.io/api-reference/pymilvus/v2.0.0rc5/install.html

**Comment by MukulKolpe** [comment]
Hey @XuanYang-cn, can I work on this issue??

**Comment by rahulmistri1997** [comment]
Hey @XuanYang-cn is this still available?

**Comment by XuanYang-cn** [comment]
> Hey @XuanYang-cn, can I work on this issue??

Thanks for the enthusiasm:heart:! This PR is currently assigned, you may find other good-first-issue here #685

Next time, just assign yourself!
