### ISSUE TITLE
check_connect decorator does nothing yet we're still using it

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#696]
This decorator https://github.com/milvus-io/pymilvus/blob/832fadeffbd1b2c28a4603e2be5ef3cb6202526b/pymilvus/client/stub.py#L37
does nothing yet we're still using it.

Better to delete it and all places using it.

**Comment by jingkl** [comment]
report PR  https://github.com/milvus-io/pymilvus/pull/698/commits/8367db3bd750459d12d1109f644cbae122bd595d
