### ISSUE TITLE
[Bug]: Need an english version of contributing_cn.md

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by DingQK** [comment]
Hi! Does the English version need to be identical in contents with the Chinese version? I want to try to translate it and it might take 1~2 days. Thank you!
/assign @DingQK
