### ISSUE TITLE
[Bug]: The format of `raises` doc comment is wrong in several methods

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/milvus-io/pymilvus/blob/3e0963ec68e6da759170b2fea5eed46d5cd456aa/pymilvus/orm/partition.py#L292

The format of this comment is wrong, it generates mis-format doc as the picture.
```
        :raises:
            RpcError: If gRPC encounter an error
            ParamError: If parameters are invalid
            BaseException: If the return result from server is not ok
```
![image](https://user-images.githubusercontent.com/51370125/138071425-c804b5fe-bac4-4c42-8cb5-774c8fd4bf7b.png)

The following format is the right one:

```
        :raises RpcError: If gRPC encounter an error.
        :raises ParamError: If parameters are invalid.
        :raises BaseException: If the return result from server is not ok.
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by avats-dev** [comment]
@XuanYang-cn I have added PR with the required changes. Please review it and let me know if you need any more tweaks. Thanks :tada:

**Comment by XuanYang-cn** [comment]
is the `Hacktoberfest` label enough for you?

If not, I'll create a new `Hactoberfest-accepted` label
