### ISSUE TITLE
[FEATURE]: get_entity_by_id is not supported  

### ISSUE THREAD

**Issue by parsa-ra** [milvus-io/pymilvus#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Suppose we want to store some kind of reference to milvuses' stored vectors, the reference internally can be simulated by entities id but the current implementation of `pymilvus.client` does not support the `get_entity_by_id` functionality from previous versions.

### Describe the solution you'd like
implement `get_entity_by_id` for `grpc` handlers

### Describe alternatives you've considered
Using previous versions of milvus driver (though not successful)

### Anything else?
There are more bunch of functions which previously implemented in older versions, checkout [here](https://pymilvus.readthedocs.io/en/latest/_modules/milvus/client/stub.html) for example.

**Comment by yanliang567** [comment]
in pymilvus 2.0, we have query as a replacement of get_entity_by_id
