### ISSUE TITLE
[FEATURE]: Need a jupyter notebook version of hello_milvus.py

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

JupyterNotebook is much more interactive than just the python script.

**Comment by DingQK** [comment]
Hi @XuanYang-cn ! I have experience in writing ipynb files and want to contribute to writing a demo for hello_milvus.py. Can I assign this issue to me and write a demo for the community? Thank you so much!

**Comment by DingQK** [comment]
Hi @XuanYang-cn ! I have experience in writing ipynb files and want to contribute to writing a demo for hello_milvus.py. Can you assign this issue to me and write a demo for the community? Thank you so much!

**Comment by DingQK** [comment]
Hi @XuanYang-cn ! I have experience in writing ipynb files and want to contribute to writing a demo for hello_milvus.py. Can I assign this issue to me and write a demo for the community? Thank you so much!

**Comment by XuanYang-cn** [comment]
@DingQK  Welcome! Feel free to open any PRs.

**Comment by DingQK** [comment]
@XuanYang-cn  Hi! I have encounter the problem of "Delete function is not implemented". I have searched existing issues and I want to make sure that right now delete function is not implemented. If it is not implemented, how should I deal with the demo of deleting entities in hello_milvus.py? Thank you so much!
