### ISSUE TITLE
[QUESTION]: 大约什么时候2.0能GA呢

### ISSUE THREAD

**Issue by nine-city** [milvus-io/pymilvus#836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

我需要根据key删除向量的功能，而根据key删除的功能只有GA版本才有，想问一下2.0GA什么时候能上线。^_^

**Comment by XuanYang-cn** [comment]
@nine-city  2.0.0 is avaliable now :tada:
