### ISSUE TITLE
pymilvus客户端的search_vectors ，无法在windows上运行，struct.unpack报错

### ISSUE THREAD

**Issue by YGodFather** [milvus-io/pymilvus#84]
[](url)
![image](https://user-images.githubusercontent.com/30761435/63919194-d9c19080-ca70-11e9-8319-2cae09daaca1.png)

**Comment by JinHai-CN** [comment]
你好，目前pymilvus只在Linux环境下验证过，并没有在Windows环境下验证通过， 谢谢!
