### ISSUE TITLE
请问vector db server在哪？是闭源的吗？

### ISSUE THREAD

**Issue by QwertyJack** [milvus-io/pymilvus#85]
RT

**Comment by JinHai-CN** [comment]
vector db server 目前尚未开放，我们预计最早会在今年四季度发布开源的 Milvus 。现在提供的试用版本，就是未来开源版本的基础。谢谢

**Comment by QwertyJack** [comment]
试用版在哪里下载？

**Comment by JinHai-CN** [comment]
这里有向量搜索的在线训练营: https://github.com/milvus-io/bootcamp， 手把手会告诉你如何操作。
另外，这里是Milvus的网站: https://milvus.io/zh-CN/，文档部分会有下载试用版和使用的全部内容。

**Comment by QwertyJack** [comment]
谢谢
