### ISSUE TITLE
[FEATURE]: losing requirements version range 

### ISSUE THREAD

**Issue by TaylorHere** [milvus-io/pymilvus#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

the dependencies described in requirements has strict version number, which will cause some packages conflicts, especially the commonly used packages like pandas, grpcio,

### Describe the solution you'd like

use >= , <= to restrict the requirements versions

**Comment by XuanYang-cn** [comment]
Good advise! To loose the requirements, we'll have to test pymilvus on different package versions and choose a proper version range.

I think these packages need to be tested: `grpcio`, `grpcio-tools`, `mmh3` and `pandas`

**Comment by XuanYang-cn** [comment]
#863
