### ISSUE TITLE
[QUESTION]: querynode crashed when doing pymilvus search

### ISSUE THREAD

**Issue by sugia** [milvus-io/pymilvus#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

The querynode crashed with log:

goroutine 10152 [semacquire]:
sync.runtime_Semacquire(0xc00d7d2a88)
/usr/local/go/src/runtime/sema.go:56
...
created by github.com/milvus-io/milvus/internal/querynode.(*queryCollection).start
/go/src/github.com/milvus-io/milvus/internal/querynode/query_collection.go:144

**Comment by XuanYang-cn** [comment]
@sugia Hi, it's better to file an issue on the Milvus repo, this repo is for python SDK only.

Anyway, crash is severe but easy to fix, it's recommended to post **the complete crash logs** at https://github.com/milvus-io/milvus/issues/new?assignees=yanliang567&labels=kind%2Fbug%2Cneeds-triage&template=bug_report.yaml&title=%5BBug%5D%3A+

The Milvus team will respond to the issues in no time. Good day!
