### ISSUE TITLE
[Bug]: no _partition_name in partition.py

### ISSUE THREAD

**Issue by sugia** [milvus-io/pymilvus#860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in this line: https://github.com/milvus-io/pymilvus/blob/master/pymilvus/orm/partition.py#L328
self._partition_name doesn't exist, it should be self._name

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
Thanks for pointing out, are you interested in fixing this problem?

**Comment by XuanYang-cn** [comment]
We're in the middle of releasing 2.0.0GA, so this issue will be open for contributors for ONE day.

If no one is interested in fixing this PR before 12:00, 1.18.2022 (Beijing timezone), I'll fix this.
