### ISSUE TITLE
[QUESTION]: does milvus 2 support inserting strings?

### ISSUE THREAD

**Issue by sugia** [milvus-io/pymilvus#877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I tried to insert string data but got error: ParamError("UnSupported data type")
https://github.com/milvus-io/pymilvus/blob/3ecafc14d0729abf615ffa95f90fe9f046b6e0c0/pymilvus/client/prepare.py#L348

Though string type is identified here:
https://github.com/milvus-io/pymilvus/blob/master/pymilvus/orm/types.py#L23

**Comment by XuanYang-cn** [comment]
@sugia  Not in Milvus2.0, `string` is scheduled to be supported on Milvus2.1
