### ISSUE TITLE
[Bug]: Init Partition with collection name and partition name instead of raise exception

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/milvus-io/pymilvus/blob/027fa27be56033a396e085f6169a1deb9fd60882/pymilvus/orm/partition.py#L27

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by kanyesthaker** [comment]
hi @XuanYang-cn, i'm new to this community and i'd be happy to take this ticket :) do you have more information on what the intended behavior should be?

**Comment by XuanYang-cn** [comment]
Should be fixed
