### ISSUE TITLE
[FEATURE]: Support `numpy.ndarray` for vector field

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by XuanYang-cn** [comment]
from #885

**Comment by XuanYang-cn** [comment]
@anukaal the robot doesn't like it when I'm trying to assign you to this issue, you are able to assign yourself though :smile_cat:

**Comment by XuanYang-cn** [comment]
@anukaal I'v double checked codes, adding these codes at `pymilvus/orm/prepare.py` would do perfectly for NumPy vector case.

![image](https://user-images.githubusercontent.com/51370125/155072958-305bd613-8dfd-4545-8f04-4b1e8da4461d.png)

I changed the code, and tested with `example/hello_milvus.py` by adding the following codes, and it worked perfectly

```python
num_entities = 3000
import numpy as np
vectors = [[random.random() for _ in range(8)] for _ in range(num_entities)]

np_vectors = np.array(vectors)
print(np_vectors)

print(fmt.format("Start inserting entities"))
entities = [
    # provide the pk field because `auto_id` is set to False
    [i for i in range(num_entities)],
    [float(random.randrange(-20, -10)) for _ in range(num_entities)],  # field random
    #  [[random.random() for _ in range(8)] for _ in range(num_entities)],  # field embeddings
    np_vectors,
]
insert_result = hello_milvus.insert(entities)

print(f"Number of entities in Milvus: {hello_milvus.num_entities}")  # check the num_entites
```

Could you make these changes and do some more tests for this issue?

**Comment by anukaal** [comment]
You can assign me for this issue

**Comment by XuanYang-cn** [comment]
> You can assign me for this issue

@anukaal oh but I've already done with this issue. It's a marvellous idea!

I've added several new `good-first-issue` on #685, and there'll be more soon, PTAL and have fun  :)
