### ISSUE TITLE
[Bug]: Incompatible with latest protoobuf 3.19

### ISSUE THREAD

**Issue by matrixji** [milvus-io/pymilvus#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Install pymilvus with 
```
python3 -m pip install pymilvus -U --user
```

`import pymilvus` failed with `AttributeError: module 'google.protobuf.internal.containers' has no attribute 'MutableMapping'`

OK with manually downgrading protobuf to 3.18.x.

### Expected Behavior

Should be ok with install with `pip install pymilvus -U`.

Guess need to use newer protoc to generate to grpc_gen code or explicit set older grpcio/protobuf in setup.py

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory): N/A
- Method of installation (Docker, or from source): python3 -m pip install pymilvus -U --user
- Milvus version (v0.3.1, or v0.4.0): 2.0.1 N/A
- Milvus configuration (Settings you made in `server_config.yaml`): N/A
```

**Comment by XuanYang-cn** [comment]
I've tried outside the virtualenv
![image](https://user-images.githubusercontent.com/51370125/158557125-9e34618a-cb31-4a91-b965-1ccfce531982.png)

and inside a virtualenv
![image](https://user-images.githubusercontent.com/51370125/158557742-762ea300-f30a-48a8-ac5c-4e81d5869ffb.png)

The both work fine.

What's your Python version and what's the `protobuf` version ?

**Comment by matrixji** [comment]
Initial face this issue with CentOS Stream 8.
I tested with virtualenv, it's OK. And I also could not reproduce from a newly installed CentOS 8 right now.
After check some issue with protobuf, I think this is an odd issue with protobuf, but not for pymilvus.

Ref: https://github.com/protocolbuffers/protobuf/issues/9409
