### ISSUE TITLE
[BUG] describe_table not sync'ed with latest proto

### ISSUE THREAD

**Issue by XuPeng-SH** [milvus-io/pymilvus#93]
**Describe the bug**
TableSchema changed in proto but sdk not sync'ed with proto changes.

**Comment by BossZou** [comment]
Hello, which version of milvus server are you using? current version of pymilvus corresponds to that of v0.4.0 of milvus server.

**Comment by XuPeng-SH** [comment]
> Hello, which version of milvus server are you using? current version of pymilvus corresponds to that of v0.4.0 of milvus server.

>0.4.0

**Comment by BossZou** [comment]
I see. You are recommended to use python package pymilvus-test instead of pymilvus. Note that you should uninstall pymilvus before installing pymilvus-test. And we'll notify you when we distribute new pymilvus version which is suitable for milvus server v0.5.0.

**Comment by BossZou** [comment]
More information in  #94

**Comment by BossZou** [comment]
fixd in #95 . Now close it
