### ISSUE TITLE
[Bug]: Insert data to field of  data type INT32 fail

### ISSUE THREAD

**Issue by baoerzhang** [milvus-io/pymilvus#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

this is my code:

> create collection -c doc_simhash2 -f index_id:INT64:primary_key -f id:INT64:doc_id -f type:INT32:doc_type -f simhash:BINARY_VECTOR:512 -d "doc_simhash_data" -p index_id -a

```
collection = Collection("doc_simhash2")
    data = [
         [10], [1], [bytes('0'*64, encoding='utf8')]
    ]
collection.insert(data)
```
the error msg:
```
pymilvus.orm.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=0, message=The types of schema and data do not match.)>
```

### Expected Behavior

insert data succeed

### Environment details

```markdown
numpy           1.22.3
pandas          1.4.2
pymilvus        2.0.2
```

### Anything else?

Please confirm this problem

**Comment by XuanYang-cn** [comment]
try this:
```
import numpy as np
collection = Collection("doc_simhash2")
    data = [
         [10], [np.int32(1)], [bytes('0'*64, encoding='utf8')]
    ]
collection.insert(data)
```

**Comment by XuanYang-cn** [comment]
closing this stale issue, feel free to reopen this any time
